// apps-benchmark/vite-solid-dynamic/solid-intlayer-app/src/components/pages/about/WhatWeMeasure.tsx
import { useIntlayer } from 'solid-intlayer';
import { For } from 'solid-js';

export default function WhatWeMeasure() {
  const content = useIntlayer('what-we-measure');

  const metrics = () => [
    {
      metric: content().bundleSizeImpact.value,
      desc: content().theAdditionalJavascriptBytesSent.value,
    },
    {
      metric: content().renderingOverhead.value,
      desc: content().howMuchExtraTimeThe.value,
    },
    {
      metric: content().hydrationCost.value,
      desc: content().duringSsrTranslationDataIs.value,
    },
    {
      metric: content().lazyLoadingEffectiveness.value,
      desc: content().whetherSplittingTranslationsByRoute.value,
    },
    {
      metric: content().localeSwitchSpeed.value,
      desc: content().howFastTheAppCan.value,
    },
  ];

  return (
    <section class="mx-auto mt-12 max-w-3xl">
      <h2 class="mb-4 text-2xl font-bold text-foreground">
        {content().whatWeMeasure}
      </h2>
      <ul class="space-y-4">
        <For each={metrics()}>
          {(m) => (
            <li class="rounded-md border border-border p-4">
              <span class="block text-sm font-bold text-primary">
                {m.metric}
              </span>
              <span class="mt-1 block text-sm text-muted-foreground">
                {m.desc}
              </span>
            </li>
          )}
        </For>
      </ul>
    </section>
  );
}

// apps-benchmark/nextjs-static/paraglide-next-app/components/pages/about/WhatWeMeasure.tsx
"use client";

import * as m from "../../../paraglide/messages";

export default function WhatWeMeasure() {
  const metrics = [
    {
      metric: m["what-we-measure.bundleSizeImpact"](),
      desc: m["what-we-measure.theAdditionalJavascriptBytesSent"](),
    },
    {
      metric: m["what-we-measure.renderingOverhead"](),
      desc: m["what-we-measure.howMuchExtraTimeThe"](),
    },
    {
      metric: m["what-we-measure.hydrationCost"](),
      desc: m["what-we-measure.duringSsrTranslationDataIs"](),
    },
    {
      metric: m["what-we-measure.lazyLoadingEffectiveness"](),
      desc: m["what-we-measure.whetherSplittingTranslationsByRoute"](),
    },
    {
      metric: m["what-we-measure.localeSwitchSpeed"](),
      desc: m["what-we-measure.howFastTheAppCan"](),
    },
  ];

  return (
    <section className="mt-12 mx-auto max-w-3xl">
      <h2 className="mb-4 text-2xl font-bold text-foreground">
        {m["what-we-measure.whatWeMeasure"]()}
      </h2>
      <ul className="space-y-4">
        {metrics.map((metricEl) => (
          <li
            key={metricEl.metric}
            className="rounded-md border border-border p-4"
          >
            <span className="block text-sm font-bold text-primary">
              {metricEl.metric}
            </span>
            <span className="block mt-1 text-sm text-muted-foreground">
              {metricEl.desc}
            </span>
          </li>
        ))}
      </ul>
    </section>
  );
}
