// apps-benchmark/vite-solid-dynamic/tolgee-app/src/components/Layout.tsx
import { useParams } from '@solidjs/router';
import { createEffect, onMount, type JSX } from 'solid-js';
import { setTolgeeLanguage, tolgee } from '../i18n';
import {
  recordHydrationDuration,
  recordRenderTime,
} from 'test-utils/browser-metrics';
import Footer from './Footer';
import Header from './Header';

export default function Layout(props: { children?: JSX.Element }) {
  const params = useParams<{ locale: string }>();
  const start = typeof performance !== 'undefined' ? performance.now() : 0;

  onMount(() => {
    recordHydrationDuration();
    recordRenderTime('AppRoot', start);
  });

  createEffect(() => {
    const loc = params.locale ?? 'en';
    void tolgee.changeLanguage(loc).then(() => {
      setTolgeeLanguage(loc);
      // Solid patches the DOM synchronously on the signal write, so html[lang]
      // (the reactivity test's end marker) follows the translated text.
      document.documentElement.lang = loc;
    });
  });

  return (
    <>
      <Header />
      {props.children}
      <Footer />
    </>
  );
}

// apps-benchmark/vite-svelte-dynamic/tolgee-app/src/components/Layout.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import {
    recordHydrationDuration,
    recordRenderTime,
  } from "test-utils/browser-metrics";
  import Footer from "./Footer.svelte";
  import Header from "./Header.svelte";

  let { locale, children } = $props<{
    locale: string;
    children: import("svelte").Snippet;
  }>();

  const renderStart =
    typeof performance !== "undefined" ? performance.now() : 0;

  onMount(() => {
    recordHydrationDuration();
    recordRenderTime("AppRoot", renderStart);
  });

  // html[lang] is set by the Tolgee "language" handler (lib/i18n/tolgee.ts)
  // once the translated text is in the DOM.
</script>

<Header />
{@render children()}
<Footer />
