// results/vite-solid-base-app/bundle/pages/FAQHeader.js
import { createComponent, template } from "solid-js/web";
var _tmpl$$1 = template(`<div class="mb-6 rounded-md border border-border bg-muted px-4 py-3 text-center text-sm text-muted-foreground">⚠️ This page contains mock data for benchmarking purposes only. It is not related to any real business or service.`);
function MockBanner() {
	return _tmpl$$1();
}
var _tmpl$ = template(`<h1 class="mb-2 text-3xl font-bold text-foreground">Frequently Asked Questions`);
var _tmpl$2 = template(`<p class="mb-10 text-muted-foreground">Everything you need to know about i18n Benchmark.`);
function FAQHeader() {
	return [
		createComponent(MockBanner, {}),
		_tmpl$(),
		_tmpl$2()
	];
}
export { FAQHeader as default };

// results/tanstack-start-react-static/base-app-vite-react/bundles/faq/FAQHeader.js
import { Fragment, jsx, jsxs } from "react/jsx-runtime";
//#region src/components/MockBanner.tsx
var MockBanner = () => jsx("div", {
	className: "mb-6 rounded-md border border-border bg-muted px-4 py-3 text-center text-sm text-muted-foreground",
	children: "⚠️ This page contains mock data for benchmarking purposes only. It is not related to any real business or service."
});
//#endregion
//#region src/components/pages/faq/FAQHeader.tsx
function FAQHeader() {
	return jsxs(Fragment, { children: [
		jsx(MockBanner, {}),
		jsx("h1", {
			className: "mb-2 text-3xl font-bold text-foreground",
			children: "Frequently Asked Questions"
		}),
		jsx("p", {
			className: "mb-10 text-muted-foreground",
			children: "Everything you need to know about i18n Benchmark."
		})
	] });
}
//#endregion
export { FAQHeader as default };
