// tanstack-start-react-static/react-i18next-app/src/i18n/i18n.ts
import i18n from "i18next";
import { initReactI18next } from "react-i18next";
import { defaultLocale } from "./config";

import en from "./locales/en.json";
import fr from "./locales/fr.json";
import es from "./locales/es.json";
import de from "./locales/de.json";
import it from "./locales/it.json";
import pt from "./locales/pt.json";
import zh from "./locales/zh.json";
import ja from "./locales/ja.json";
import ko from "./locales/ko.json";
import ru from "./locales/ru.json";

i18n.use(initReactI18next).init({
  resources: {
    en: { translation: en },
    fr: { translation: fr },
    es: { translation: es },
    de: { translation: de },
    it: { translation: it },
    pt: { translation: pt },
    zh: { translation: zh },
    ja: { translation: ja },
    ko: { translation: ko },
    ru: { translation: ru },
  },
  lng: defaultLocale,
  fallbackLng: defaultLocale,
  interpolation: {
    escapeValue: false, // React already escapes
  },
});

export default i18n;

// apps-benchmark/vite-solid-static/i18next-app/src/i18n.ts
import i18next from "i18next";
import { createSignal } from "solid-js";
import en from "../locales/en.json";
import fr from "../locales/fr.json";
import es from "../locales/es.json";
import de from "../locales/de.json";
import it from "../locales/it.json";
import pt from "../locales/pt.json";
import zh from "../locales/zh.json";
import ja from "../locales/ja.json";
import ko from "../locales/ko.json";
import ru from "../locales/ru.json";

export const [t, setT] = createSignal(i18next.t.bind(i18next));

i18next.init({
  fallbackLng: "en",
  resources: {
    en: {
      translation: en,
    },
    fr: {
      translation: fr,
    },
    es: {
      translation: es,
    },
    de: {
      translation: de,
    },
    it: {
      translation: it,
    },
    pt: {
      translation: pt,
    },
    zh: {
      translation: zh,
    },
    ja: {
      translation: ja,
    },
    ko: {
      translation: ko,
    },
    ru: {
      translation: ru,
    },
  },
});

setT(() => i18next.t.bind(i18next));

export { i18next };
