// apps-benchmark/vite-solid-scoped-static/i18next-app/src/pages/Blog.tsx
import { lazy, Suspense } from "solid-js";
import { useNamespace } from "../i18n";

useNamespace(
  import.meta.glob<Record<string, unknown>>("../../locales/*/blog.json", {
    eager: true,
    import: "default",
  }),
);

const BlogHeader = lazy(() => import("../components/pages/blog/BlogHeader"));
const BlogList = lazy(() => import("../components/pages/blog/BlogList"));

export default function Blog() {
  return (
    <div class="container py-16">
      <Suspense fallback={<div class="h-48 animate-pulse bg-muted/20" />}>
        <BlogHeader />
      </Suspense>

      <Suspense fallback={<div class="h-96 animate-pulse bg-muted/20" />}>
        <BlogList />
      </Suspense>
    </div>
  );
}

// apps-benchmark/vite-vue-scoped-static/fluent-vue-app/src/pages/Blog.vue
<script setup lang="ts">
import { defineAsyncComponent } from "vue";
import { useNamespace } from "../i18n";

useNamespace(
  import.meta.glob<string>("../locales/*/blog.ftl", {
    eager: true,
    query: "?raw",
    import: "default",
  }),
);

const BlogHeader = defineAsyncComponent(() => import("../components/pages/blog/BlogHeader.vue"));
const BlogList = defineAsyncComponent(() => import("../components/pages/blog/BlogList.vue"));
</script>

<template>
  <div class="container py-16">
    <Suspense>
      <BlogHeader />
      <template #fallback>
        <div class="h-48 animate-pulse bg-muted/20" />
      </template>
    </Suspense>

    <Suspense>
      <BlogList />
      <template #fallback>
        <div class="h-96 animate-pulse bg-muted/20" />
      </template>
    </Suspense>
  </div>
</template>
