// tanstack-start-react-scoped-static/intlayer-app/src/routes/$locale/about.tsx
import { createFileRoute } from "@tanstack/react-router";
import { lazy, Suspense } from "react";

const AboutHeader = lazy(
  () => import("../../components/pages/about/AboutHeader"),
);
const AboutGrid = lazy(() => import("../../components/pages/about/AboutGrid"));
const WhatWeMeasure = lazy(
  () => import("../../components/pages/about/WhatWeMeasure"),
);

export const Route = createFileRoute("/$locale/about")({
  component: About,
});

function About() {
  return (
    <div className="container py-16">
      <Suspense fallback={<div className="h-48 animate-pulse bg-muted/20" />}>
        <AboutHeader />
      </Suspense>

      <Suspense fallback={<div className="h-64 animate-pulse bg-muted/20" />}>
        <AboutGrid />
      </Suspense>

      <Suspense fallback={<div className="h-96 animate-pulse bg-muted/20" />}>
        <WhatWeMeasure />
      </Suspense>
    </div>
  );
}

// apps-benchmark/vite-solid-base-app/src/pages/About.tsx
import { lazy, Suspense } from "solid-js";

const AboutHeader = lazy(() => import("../components/pages/about/AboutHeader"));
const AboutGrid = lazy(() => import("../components/pages/about/AboutGrid"));
const WhatWeMeasure = lazy(
  () => import("../components/pages/about/WhatWeMeasure"),
);

export default function About() {
  return (
    <div class="container py-16">
      <Suspense fallback={<div class="h-48 animate-pulse bg-muted/20" />}>
        <AboutHeader />
      </Suspense>

      <Suspense fallback={<div class="h-64 animate-pulse bg-muted/20" />}>
        <AboutGrid />
      </Suspense>

      <Suspense fallback={<div class="h-96 animate-pulse bg-muted/20" />}>
        <WhatWeMeasure />
      </Suspense>
    </div>
  );
}
