// apps-benchmark/nextjs-static/next-intlayer-app/src/app/[locale]/faq/page.tsx
import { Suspense } from "react";
import FAQHeader from "@/components/pages/faq/FAQHeader";
import FAQList from "@/components/pages/faq/FAQList";
import type { NextPageIntlayer } from "next-intlayer";

const FAQ: NextPageIntlayer = () => (
  <div className="container py-16">
    <Suspense fallback={<div className="h-48 animate-pulse bg-muted/20" />}>
      <FAQHeader />
    </Suspense>

    <Suspense fallback={<div className="h-96 animate-pulse bg-muted/20" />}>
      <FAQList />
    </Suspense>
  </div>
);

export default FAQ;

// apps-benchmark/vite-solid-base-app/src/pages/FAQ.tsx
import { lazy, Suspense } from "solid-js";

const FAQHeader = lazy(() => import("../components/pages/faq/FAQHeader"));
const FAQList = lazy(() => import("../components/pages/faq/FAQList"));

export default function FAQ() {
  return (
    <div class="container py-16">
      <Suspense fallback={<div class="h-48 animate-pulse bg-muted/20" />}>
        <FAQHeader />
      </Suspense>

      <Suspense fallback={<div class="h-96 animate-pulse bg-muted/20" />}>
        <FAQList />
      </Suspense>
    </div>
  );
}
