// apps-benchmark/vite-react-static/tolgee-app/src/main.tsx
import { StrictMode } from "react";
import { createRoot } from "react-dom/client";
import App from "./App";
import "./styles.css";

if (
  typeof performance !== "undefined" &&
  typeof performance.mark === "function"
) {
  performance.mark("hydration_start");
}

createRoot(document.getElementById("root")!).render(
  <StrictMode>
    <App />
  </StrictMode>,
);

// apps-benchmark/vite-solid-dynamic/i18next-app/src/index.tsx
/* @refresh reload */
import { render } from "solid-js/web";
import App from "./App.tsx";
import "./styles.css";

if (typeof window !== "undefined") {
  if (window.location.pathname === "/" || window.location.pathname === "") {
    window.history.replaceState(null, "", "/en");
  }
}

const root = document.getElementById("root");

render(() => <App />, root!);
