// apps-benchmark/tanstack-start-react-scoped-static/tolgee-app/src/routes/$locale/products.tsx
import { createFileRoute } from "@tanstack/react-router";
import { lazy, Suspense } from "react";

const ProductsHeader = lazy(
  () => import("../../components/pages/products/ProductsHeader"),
);
const ProductsGrid = lazy(
  () => import("../../components/pages/products/ProductsGrid"),
);

export const Route = createFileRoute("/$locale/products")({
  component: Products,
});

function Products() {
  return (
    <div className="container py-16">
      <Suspense fallback={<div className="h-48 animate-pulse bg-muted/20" />}>
        <ProductsHeader />
      </Suspense>

      <Suspense fallback={<div className="h-96 animate-pulse bg-muted/20" />}>
        <ProductsGrid />
      </Suspense>
    </div>
  );
}

// apps-benchmark/vite-solid-dynamic/i18next-app/src/pages/Products.tsx
import { lazy, Suspense } from "solid-js";

const ProductsHeader = lazy(
  () => import("../components/pages/products/ProductsHeader"),
);
const ProductsGrid = lazy(
  () => import("../components/pages/products/ProductsGrid"),
);

export default function Products() {
  return (
    <div class="container py-16">
      <Suspense fallback={<div class="h-48 animate-pulse bg-muted/20" />}>
        <ProductsHeader />
      </Suspense>

      <Suspense fallback={<div class="h-96 animate-pulse bg-muted/20" />}>
        <ProductsGrid />
      </Suspense>
    </div>
  );
}
