// apps-benchmark/vite-solid-static/paraglide-js-app/src/components/ThemeToggle.tsx
import { createEffect, createSignal, onMount } from "solid-js";
import * as m from "../paraglide/messages";

type ThemeMode = "light" | "dark" | "auto";

function getInitialMode(): ThemeMode {
  if (typeof window === "undefined") {
    return "auto";
  }

  const stored = window.localStorage.getItem("theme");
  if (stored === "light" || stored === "dark" || stored === "auto") {
    return stored;
  }

  return "auto";
}

function applyThemeMode(mode: ThemeMode) {
  const prefersDark = window.matchMedia("(prefers-color-scheme: dark)").matches;
  const resolved = mode === "auto" ? (prefersDark ? "dark" : "light") : mode;

  document.documentElement.classList.remove("light", "dark");
  document.documentElement.classList.add(resolved);

  if (mode === "auto") {
    document.documentElement.removeAttribute("data-theme");
  } else {
    document.documentElement.setAttribute("data-theme", mode);
  }

  document.documentElement.style.colorScheme = resolved;
}

export default function ThemeToggle() {
  const [mode, setMode] = createSignal<ThemeMode>("auto");

  onMount(() => {
    const initialMode = getInitialMode();
    setMode(initialMode);
    applyThemeMode(initialMode);
  });

  createEffect(() => {
    if (mode() !== "auto") {
      return;
    }

    const media = window.matchMedia("(prefers-color-scheme: dark)");
    const onChange = () => applyThemeMode("auto");

    media.addEventListener("change", onChange);
    return () => {
      media.removeEventListener("change", onChange);
    };
  });

  function toggleMode() {
    const current = mode();
    const nextMode: ThemeMode =
      current === "light" ? "dark" : current === "dark" ? "auto" : "light";
    setMode(nextMode);
    applyThemeMode(nextMode);
    window.localStorage.setItem("theme", nextMode);
  }

  const label = () =>
    mode() === "auto"
      ? m.themeToggle_labelAuto()
      : m.themeToggle_labelOther({ mode: mode() });

  const buttonText = () =>
    mode() === "auto"
      ? m.themeToggle_auto()
      : mode() === "dark"
        ? m.themeToggle_dark()
        : m.themeToggle_light();

  return (
    <button
      type="button"
      onClick={toggleMode}
      aria-label={label()}
      title={label()}
      class="rounded-md border border-border bg-accent px-3 py-1.5 text-xs font-medium text-foreground transition-colors hover:bg-accent/80"
    >
      {buttonText()}
    </button>
  );
}

// apps-benchmark/vite-svelte-static/paraglide-js-app/src/components/ThemeToggle.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import { m } from "../paraglide/messages";

  type ThemeMode = "light" | "dark" | "auto";

  function getInitialMode(): ThemeMode {
    if (typeof window === "undefined") return "auto";
    const stored = window.localStorage.getItem("theme");
    if (stored === "light" || stored === "dark" || stored === "auto") {
      return stored;
    }
    return "auto";
  }

  function applyThemeMode(mode: ThemeMode) {
    const prefersDark = window.matchMedia(
      "(prefers-color-scheme: dark)",
    ).matches;
    const resolved = mode === "auto" ? (prefersDark ? "dark" : "light") : mode;

    document.documentElement.classList.remove("light", "dark");
    document.documentElement.classList.add(resolved);

    if (mode === "auto") {
      document.documentElement.removeAttribute("data-theme");
    } else {
      document.documentElement.setAttribute("data-theme", mode);
    }

    document.documentElement.style.colorScheme = resolved;
  }

  let mode = $state<ThemeMode>("auto");

  onMount(() => {
    const initialMode = getInitialMode();
    mode = initialMode;
    applyThemeMode(initialMode);
  });

  $effect(() => {
    if (mode !== "auto") return;

    const media = window.matchMedia("(prefers-color-scheme: dark)");
    const onChange = () => applyThemeMode("auto");
    media.addEventListener("change", onChange);
    return () => media.removeEventListener("change", onChange);
  });

  function toggleMode() {
    const nextMode: ThemeMode =
      mode === "light" ? "dark" : mode === "dark" ? "auto" : "light";
    mode = nextMode;
    applyThemeMode(nextMode);
    window.localStorage.setItem("theme", nextMode);
  }

  const label = $derived(
    mode === "auto"
      ? m.themeToggle_labelAuto()
      : m.themeToggle_labelOther({ mode }),
  );

  const buttonText = $derived(
    mode === "auto"
      ? m.themeToggle_auto()
      : mode === "dark"
        ? m.themeToggle_dark()
        : m.themeToggle_light(),
  );
</script>

<button
  type="button"
  onclick={toggleMode}
  aria-label={label}
  title={label}
  class="rounded-md border border-border bg-accent px-3 py-1.5 text-xs font-medium text-foreground transition-colors hover:bg-accent/80"
>
  {buttonText}
</button>
