// apps-benchmark/vite-solid-dynamic/i18next-app/src/components/LocaleSwitcher.tsx
import { useLocation, useNavigate, useParams } from "@solidjs/router";
import { For } from "solid-js";
import { getLocaleName, locales } from "../i18n/config";

export default function LocaleSwitcher() {
  const params = useParams<{ locale: string }>();
  const navigate = useNavigate();
  const location = useLocation();

  const handleLocaleChange = (newLocale: string) => {
    const pathname = location.pathname;
    const newPath = pathname.replace(/^\/[^/]+/, `/${newLocale}`);
    navigate(`${newPath}${location.search}${location.hash}`);
  };

  return (
    <div class="flex items-center gap-2">
      <select
        value={params.locale ?? "en"}
        onChange={(e) => handleLocaleChange(e.currentTarget.value)}
        class="h-8 rounded-md border border-border bg-card px-2 text-xs font-medium transition-colors focus:outline-none focus:ring-1 focus:ring-primary"
      >
        <For each={locales}>
          {(localeItem) => (
            <option value={localeItem}>{getLocaleName(localeItem)}</option>
          )}
        </For>
      </select>
    </div>
  );
}

// vite+react-static/base-app/src/components/LocaleSwitcher.tsx
import { useLocation, useNavigate, useParams } from "react-router-dom";
import { getLocaleName, locales } from "../i18n/config";

export default function LocaleSwitcher() {
  const { locale = "en" } = useParams();
  const navigate = useNavigate();
  const location = useLocation();

  const handleLocaleChange = (newLocale: string) => {
    const newPath = location.pathname.replace(
      /^\/[^/]+/,
      `/${newLocale}`,
    );
    navigate(newPath + location.search + location.hash);
  };

  return (
    <div className="flex items-center gap-2">
      <select
        value={locale}
        onChange={(e) => handleLocaleChange(e.target.value)}
        className="h-8 rounded-md border border-border bg-card px-2 text-xs font-medium focus:outline-none focus:ring-1 focus:ring-primary transition-colors"
      >
        {locales.map((localeItem) => (
          <option key={localeItem} value={localeItem}>
            {getLocaleName(localeItem)}
          </option>
        ))}
      </select>
    </div>
  );
}
