// results/tanstack-start-react-static/static-paraglide-app/bundles/Shared/LocaleSwitcher_min.js
import "react";
import { useNavigate as e, useParams as t } from "@tanstack/react-router";
import { Fragment as n, jsx as r } from "react/jsx-runtime";
//#region src/paraglide/runtime.js
var i = {}, a = [
	"en",
	"fr",
	"es",
	"de",
	"it",
	"pt",
	"zh",
	"ja",
	"ko",
	"ru"
], o = "PARAGLIDE_LOCALE", s = 3456e4, c = [
	"cookie",
	"globalVariable",
	"baseLocale"
], l = [], u, d;
function f(e) {
	if (l.length === 0) return;
	let t = typeof e == "string" ? e : e.href;
	if (u === t) return d;
	let n = new URL(t, "http://dummy.com"), r;
	for (let e of l) if (new i(e.match, n.href).exec(n.href)) {
		r = e;
		break;
	}
	return u = t, d = r, r;
}
function p(e) {
	let t = f(e);
	return t && t.exclude !== !0 && Array.isArray(t.strategy) ? t.strategy : c;
}
var m = void 0;
globalThis.__paraglide = globalThis.__paraglide ?? {}, globalThis.__paraglide.ssr = globalThis.__paraglide.ssr ?? {};
var h, g = !1, _ = () => {
	if (m) {
		let e = m?.getStore()?.locale;
		if (e) return e;
	}
	let e = c;
	typeof window < "u" && window.location?.href && (e = p(window.location.href));
	let t = v(e, typeof window < "u" ? window.location?.href : void 0);
	if (t) return g || (h = t, g = !0, b(t, { reload: !1 })), t;
	throw Error("No locale found. Read the docs https://inlang.com/m/gerre34r/library-inlang-paraglideJs/errors#no-locale-found");
};
function v(e, t) {
	let n;
	for (let t of e) {
		if (t === "cookie") n = C();
		else if (t === "baseLocale") n = "en";
		else if (t === "globalVariable" && h !== void 0) n = h;
		else if (T(t) && w.has(t)) {
			let e = w.get(t);
			if (e) {
				let t = e.getLocale();
				if (t instanceof Promise) continue;
				if (t !== void 0) return S(t);
			}
		}
		let e = x(n);
		if (e) return e;
	}
}
var y = (e) => {
	e ? window.location.href = e : window.location.reload();
}, b = (e, t) => {
	let n = {
		reload: !0,
		...t
	}, r;
	try {
		r = _();
	} catch {}
	let i = [], a = c;
	typeof window < "u" && window.location?.href && (a = p(window.location.href));
	for (let t of a) if (t === "globalVariable") h = e;
	else if (t === "cookie") {
		if (typeof document > "u" || typeof window > "u") continue;
		let t = `${o}=${e}; path=/; max-age=${s}`;
		document.cookie = t;
	} else if (t === "baseLocale") continue;
	else if (T(t) && w.has(t)) {
		let n = w.get(t);
		if (n) {
			let r = n.setLocale(e);
			r instanceof Promise && (r = r.catch((e) => {
				throw Error(`Custom strategy "${t}" setLocale failed.`, { cause: e });
			}), i.push(r));
		}
	}
	let l = () => {
		n.reload && window.location && e !== r && y(void 0);
	};
	if (i.length) return Promise.all(i).then(() => {
		l();
	});
	l();
};
function x(e) {
	if (typeof e != "string") return;
	let t = e.toLowerCase();
	for (let e of a) if (e.toLowerCase() === t) return e;
}
function S(e) {
	let t = x(e);
	if (t) return t;
	throw Error(`Invalid locale: ${e}. Expected one of: ${a.join(", ")}`);
}
function C() {
	if (typeof document > "u" || !document.cookie) return;
	let e = document.cookie.match(RegExp(`(^| )${o}=([^;]+)`))?.[2];
	return x(e);
}
var w = /* @__PURE__ */ new Map();
function T(e) {
	return typeof e == "string" && /^custom-[A-Za-z0-9_-]+$/.test(e);
}
//#endregion
//#region src/components/LocaleSwitcher.tsx
function E() {
	let n = t({ strict: !1 }).locale ?? "en", i = e(), o = (e) => {
		try {
			let t = new Intl.DisplayNames([e], { type: "language" }).of(e);
			return t ? t.charAt(0).toUpperCase() + t.slice(1) : e;
		} catch {
			return e.toUpperCase();
		}
	}, s = (e) => {
		i({
			to: ".",
			params: (t) => ({
				...t,
				locale: e
			})
		});
	};
	return /* @__PURE__ */ r("div", {
		className: "flex items-center gap-2",
		children: /* @__PURE__ */ r("select", {
			value: n,
			onChange: (e) => s(e.target.value),
			className: "h-8 rounded-md border border-border bg-card px-2 text-xs font-medium focus:outline-none focus:ring-1 focus:ring-primary transition-colors",
			children: a.map((e) => /* @__PURE__ */ r("option", {
				value: e,
				children: o(e)
			}, e))
		})
	});
}
//#endregion
//#region scripts/Wrapper.tsx
b("en", { reload: !1 });
function D({ children: e }) {
	return /* @__PURE__ */ r(n, { children: e });
}
//#endregion
//#region src/components/LocaleSwitcher.wrapper.tsx
function O() {
	return /* @__PURE__ */ r(D, { children: /* @__PURE__ */ r(E, {}) });
}
//#endregion
export { O as default };

// results/vite-solid-intlayer-dynamic/bundle/Shared/LocaleSwitcher_min.js
import { createComponent as e, effect as t, insert as n, template as r } from "solid-js/web";
import { useLocation as i, useNavigate as a, useParams as o } from "@solidjs/router";
import { For as s } from "solid-js";
var c = [
	"en",
	"fr",
	"es",
	"de",
	"it",
	"pt",
	"zh",
	"ja",
	"ko",
	"ru"
], l = (e) => {
	try {
		let t = new Intl.DisplayNames([e], { type: "language" }).of(e);
		return t ? t.charAt(0).toUpperCase() + t.slice(1) : e;
	} catch {
		return e.toUpperCase();
	}
}, u = r("<div class=\"flex items-center gap-2\"><select class=\"h-8 rounded-md border border-border bg-card px-2 text-xs font-medium transition-colors focus:outline-none focus:ring-1 focus:ring-primary\">"), d = r("<option>");
function f() {
	let r = o(), f = a(), p = i(), m = (e) => {
		let t = p.pathname.replace(/^\/[^/]+/, `/${e}`);
		f(`${t}${p.search}${p.hash}`);
	};
	return (() => {
		var i = u(), a = i.firstChild;
		return a.addEventListener("change", (e) => m(e.currentTarget.value)), n(a, e(s, {
			each: c,
			children: (e) => (() => {
				var t = d();
				return t.value = e, n(t, () => l(e)), t;
			})()
		})), t(() => a.value = r.locale ?? "en"), i;
	})();
}
export { f as default };
