// apps-benchmark/vite-solid-base-app/src/pages/FAQ.tsx
import { lazy, Suspense } from "solid-js";

const FAQHeader = lazy(() => import("../components/pages/faq/FAQHeader"));
const FAQList = lazy(() => import("../components/pages/faq/FAQList"));

export default function FAQ() {
  return (
    <div class="container py-16">
      <Suspense fallback={<div class="h-48 animate-pulse bg-muted/20" />}>
        <FAQHeader />
      </Suspense>

      <Suspense fallback={<div class="h-96 animate-pulse bg-muted/20" />}>
        <FAQList />
      </Suspense>
    </div>
  );
}

// tanstack-start-react-dynamic/tolgee-app/src/routes/$locale/faq.tsx
import { createFileRoute } from "@tanstack/react-router";
import { lazy, Suspense } from "react";

const FAQHeader = lazy(() => import("../../components/pages/faq/FAQHeader"));
const FAQList = lazy(() => import("../../components/pages/faq/FAQList"));

export const Route = createFileRoute("/$locale/faq")({
  component: FAQ,
});

function FAQ() {
  return (
    <div className="container py-16">
      <Suspense fallback={<div className="h-48 animate-pulse bg-muted/20" />}>
        <FAQHeader />
      </Suspense>

      <Suspense fallback={<div className="h-96 animate-pulse bg-muted/20" />}>
        <FAQList />
      </Suspense>
    </div>
  );
}
