// results/tanstack-start-react-static/intlayer-app/bundles/pricing/PricingTiers_min.js
import { Fragment as e, createContext as t, createElement as n, isValidElement as r, lazy as i, useContext as a, useEffect as o, useMemo as s, useRef as c, useState as ee } from "react";
import { Fragment as l, jsx as u, jsxs as d } from "react/jsx-runtime";
var f = {
	key: "pricing-tiers",
	content: {
		nodeType: "translation",
		translation: {
			en: {
				y: "Starter",
				r: "$0",
				l: "forever",
				c: {
					fields: [],
					nodeType: "insertion",
					insertion: "{runs} benchmark runs/day"
				},
				o: {
					fields: [],
					nodeType: "insertion",
					insertion: "{libs} libraries"
				},
				e: "Community support",
				w: "Public results",
				v: "Pro",
				s: "$29",
				p: "/month",
				aa: "Unlimited runs",
				a: "All libraries",
				t: "Priority support",
				u: "Private results",
				d: "CI integration",
				n: "Historical data",
				j: "Enterprise",
				g: "Custom",
				k: "Everything in Pro",
				q: "On-premise option",
				x: "SSO & SAML",
				i: "Dedicated account manager",
				h: "Custom SLAs",
				b: "Audit logs",
				z: "Training sessions",
				f: "Contact Sales",
				m: "Get Started"
			},
			fr: {
				y: "Starter",
				r: "0 $",
				l: "pour toujours",
				c: {
					fields: [],
					nodeType: "insertion",
					insertion: "{runs} lancements de benchmark/jour"
				},
				o: {
					fields: [],
					nodeType: "insertion",
					insertion: "{libs} bibliothèques"
				},
				e: "Support de la communauté",
				w: "Résultats publics",
				v: "Pro",
				s: "29 $",
				p: "/mois",
				aa: "Lancements illimités",
				a: "Toutes les bibliothèques",
				t: "Support prioritaire",
				u: "Résultats privés",
				d: "Intégration CI",
				n: "Données historiques",
				j: "Entreprise",
				g: "Custom",
				k: "Tout dans Pro",
				q: "Option sur site",
				x: "SSO & SAML",
				i: "Gestionnaire de compte dédié",
				h: "SLA personnalisés",
				b: "Journaux d'audit",
				z: "Sessions de formation",
				f: "Contacter les ventes",
				m: "Commencer"
			},
			es: {
				y: "Starter",
				r: "0 $",
				l: "para siempre",
				c: {
					fields: [],
					nodeType: "insertion",
					insertion: "{runs} ejecuciones de benchmark/día"
				},
				o: {
					fields: [],
					nodeType: "insertion",
					insertion: "{libs} bibliotecas"
				},
				e: "Soporte de la comunidad",
				w: "Resultados públicos",
				v: "Pro",
				s: "29 $",
				p: "/mes",
				aa: "Ejecuciones ilimitadas",
				a: "Todas las bibliotecas",
				t: "Soporte prioritario",
				u: "Résultats privés",
				d: "Integración de CI",
				n: "Datos históricos",
				j: "Personalizado",
				g: "Custom",
				k: "Todo en Pro",
				q: "Opción local",
				x: "SSO y SAML",
				i: "Gerente de cuenta dedicado",
				h: "SLA personalizados",
				b: "Registros de auditoría",
				z: "Sesiones de formación",
				f: "Contactar a Ventas",
				m: "Empezar"
			},
			de: {
				y: "Starter",
				r: "0 $",
				l: "für immer",
				c: {
					fields: [],
					nodeType: "insertion",
					insertion: "{runs} Benchmark-Läufe/Tag"
				},
				o: {
					fields: [],
					nodeType: "insertion",
					insertion: "{libs} Bibliotheken"
				},
				e: "Community-Support",
				w: "Öffentliche Ergebnisse",
				v: "Pro",
				s: "29 $",
				p: "/Monat",
				aa: "Unbegrenzte Läufe",
				a: "Alle Bibliotheken",
				t: "Prioritäts-Support",
				u: "Private Ergebnisse",
				d: "CI-Integration",
				n: "Historische Daten",
				j: "Enterprise",
				g: "Benutzerdefiniert",
				k: "Alles in Pro",
				q: "On-Premise-Option",
				x: "SSO & SAML",
				i: "Dedizierter Account-Manager",
				h: "Benutzerdefinierte SLAs",
				b: "Audit-Logs",
				z: "Schulungssitzungen",
				f: "Vertrieb kontaktieren",
				m: "Erste Schritte"
			},
			it: {
				y: "Starter",
				r: "0 $",
				l: "per sempre",
				c: {
					fields: [],
					nodeType: "insertion",
					insertion: "{runs} esecuzioni di benchmark/giorno"
				},
				o: {
					fields: [],
					nodeType: "insertion",
					insertion: "{libs} librerie"
				},
				e: "Supporto della comunità",
				w: "Risultati pubblici",
				v: "Pro",
				s: "29 $",
				p: "/mese",
				aa: "Esecuzioni illimitate",
				a: "Tutte le librerie",
				t: "Supporto prioritario",
				u: "Risultati privati",
				d: "Integrazione CI",
				n: "Dati storici",
				j: "Enterprise",
				g: "Custom",
				k: "Tutto in Pro",
				q: "Opzione on-premise",
				x: "SSO e SAML",
				i: "Account manager dedicato",
				h: "SLA personalizzati",
				b: "Log di audit",
				z: "Sessioni di formazione",
				f: "Contatta le vendite",
				m: "Inizia ora"
			},
			pt: {
				y: "Iniciante",
				r: "0 $",
				l: "para sempre",
				c: {
					fields: [],
					nodeType: "insertion",
					insertion: "{runs} execuções de benchmark/dia"
				},
				o: {
					fields: [],
					nodeType: "insertion",
					insertion: "{libs} bibliotecas"
				},
				e: "Suporte da comunidade",
				w: "Resultados públicos",
				v: "Pro",
				s: "29 $",
				p: "/mês",
				aa: "Execuções ilimitadas",
				a: "Todas as bibliotecas",
				t: "Suporte prioritário",
				u: "Resultados privados",
				d: "Integração de CI",
				n: "Dados históricos",
				j: "Personalizado",
				g: "Personalizado",
				k: "Tudo no Pro",
				q: "Opção on-premise",
				x: "SSO e SAML",
				i: "Gerente de conta dedicado",
				h: "SLAs personalizados",
				b: "Logs de auditoria",
				z: "Sessões de treinamento",
				f: "Contatar Vendas",
				m: "Começar"
			},
			zh: {
				y: "Starter",
				r: "0 $",
				l: "永久",
				c: {
					fields: [],
					nodeType: "insertion",
					insertion: "每天 {runs} 次基准测试运行"
				},
				o: {
					fields: [],
					nodeType: "insertion",
					insertion: "{libs} 个库"
				},
				e: "社区支持",
				w: "公共结果",
				v: "Pro",
				s: "29 $",
				p: "/月",
				aa: "无限运行",
				a: "所有库",
				t: "优先支持",
				u: "私人结果",
				d: "CI 集成",
				n: "历史数据",
				j: "企业版",
				g: "定制价格",
				k: "Pro 计划中的一切",
				q: "本地部署选项",
				x: "SSO & SAML",
				i: "专属大客户经理",
				h: "定制 SLA",
				b: "审核日志",
				z: "培训会议",
				f: "联系销售人员",
				m: "开始使用"
			},
			ja: {
				y: "スターター",
				r: "0 $",
				l: "永久",
				c: {
					fields: [],
					nodeType: "insertion",
					insertion: "毎日 {runs} 回のベンチマーク実行"
				},
				o: {
					fields: [],
					nodeType: "insertion",
					insertion: "{libs} 個のライブラリ"
				},
				e: "コミュニティサポート",
				w: "公開結果",
				v: "プロ",
				s: "29 $",
				p: "/月",
				aa: "無限の実行",
				a: "すべてのライブラリ",
				t: "優先サポート",
				u: "プライベート結果",
				d: "CI 統合",
				n: "履歴データ",
				j: "エンタープライズ",
				g: "カスタム価格",
				k: "Pro のすべて",
				q: "オンプレミスオプション",
				x: "SSO & SAML",
				i: "専任のアカウントマネージャー",
				h: "カスタム SLA",
				b: "監査ログ",
				z: "トレーニングセッション",
				f: "営業に問い合わせる",
				m: "使ってみる"
			},
			ko: {
				y: "스타터",
				r: "0 $",
				l: "영구적",
				c: {
					fields: [],
					nodeType: "insertion",
					insertion: "하루 {runs} 회의 벤치마크 실행"
				},
				o: {
					fields: [],
					nodeType: "insertion",
					insertion: "{libs} 개의 라이브러리"
				},
				e: "커뮤니티 지원",
				w: "공개 결과",
				v: "프로",
				s: "29 $",
				p: "/월",
				aa: "무제한 실행",
				a: "모든 라이브러리",
				t: "우선 지원",
				u: "비공개 결과",
				d: "CI 통합",
				n: "기록 데이터",
				j: "엔터프라이즈",
				g: "맞춤형 가격",
				k: "프로의 모든 기능",
				q: "온프레미스 옵션",
				x: "SSO & SAML",
				i: "전담 어카운트 매니저",
				h: "사용자 지정 SLA",
				b: "감사 로그",
				z: "교육 세션",
				f: "영업 문의",
				m: "시작하기"
			},
			ru: {
				y: "Starter",
				r: "0 $",
				l: "навсегда",
				c: {
					fields: [],
					nodeType: "insertion",
					insertion: "{runs} запусков бенчмарка в день"
				},
				o: {
					fields: [],
					nodeType: "insertion",
					insertion: "{libs} библиотек"
				},
				e: "Сообщество поддержки",
				w: "Публичные результаты",
				v: "Pro",
				s: "29 $",
				p: "/месяц",
				aa: "Неограниченное количество запусков",
				a: "Все библиотеки",
				t: "Приоритетная поддержка",
				u: "Приватные результаты",
				d: "Интеграция с CI",
				n: "Исторические данные",
				j: "Корпоративный",
				g: "Индивидуальная цена",
				k: "Все возможности Pro",
				q: "Локальное развертывание",
				x: "SSO и SAML",
				i: "Выделенный менеджер",
				h: "Индивидуальные SLA",
				b: "Журналы аудита",
				z: "Сессии обучения",
				f: "Связаться с отделом продаж",
				m: "Начать"
			}
		}
	}
}, p = {
	locales: [
		"en",
		"fr",
		"es",
		"de",
		"it",
		"pt",
		"zh",
		"ja",
		"ko",
		"ru"
	],
	defaultLocale: "en"
}, m = {
	mode: "prefix-no-default",
	storage: {
		cookies: [{
			name: "INTLAYER_LOCALE",
			attributes: {}
		}],
		headers: [{ name: "x-intlayer-locale" }]
	},
	basePath: ""
}, h = ({ children: e, value: t, additionalProps: n }) => {
	let i = r(e) ? e : /* @__PURE__ */ u(l, { children: e });
	return new Proxy(i, { get(e, r, i) {
		return r === "value" ? t : n && Object.keys(n).includes(r) ? n[r] : Reflect.get(e, r, i);
	} });
}, g = (e) => {
	if (typeof e != "object" || !e) return e;
	let { type: t, props: r } = ((e) => {
		let t = e.props?.children;
		if (Array.isArray(t)) {
			let r = t.map((e, t) => {
				let r = g(e);
				if (typeof r == "object" && r && "type" in r) {
					let e = r;
					return n(e.type, {
						...e.props,
						key: t
					}, ...Array.isArray(e.props?.children) ? e.props.children : e.props?.children === void 0 ? [] : [e.props.children]);
				}
				return r;
			});
			return {
				...e,
				props: {
					...e.props,
					children: r
				}
			};
		} else if (t != null) {
			let n = g(t);
			return {
				...e,
				props: {
					...e.props,
					children: [n]
				}
			};
		}
		return {
			...e,
			props: {
				...e.props,
				children: []
			}
		};
	})(e);
	return n(t ?? "span", r, ...r.children);
}, te = "translation", _ = "insertion", v = "object", ne = "array", y = (e, t) => {
	for (let n of t.plugins ?? []) if (n.canHandle(e)) return n.transform(e, t, (e, t) => y(e, t));
	if (typeof e != "object" || !e || e.$$typeof !== void 0 || e.__v_isVNode !== void 0 || e._isVNode !== void 0 || e.isJSX !== void 0 || typeof e == "function") return e;
	if (Array.isArray(e)) return e.map((e, n) => y(e, {
		...t,
		children: e,
		keyPath: [...t.keyPath, {
			type: ne,
			key: n
		}]
	}));
	let n = {};
	for (let r in e) {
		let i = {
			...t,
			children: e[r],
			keyPath: [...t.keyPath, {
				type: v,
				key: r
			}]
		};
		n[r] = y(e[r], i);
	}
	return n;
}, re = (e, t) => e.replace(/\{\{\s*(.*?)\s*\}\}/g, (e, n) => (t[n.trim()] ?? "").toString()), b = (e) => {
	if (typeof e != "object" || !e || typeof e.then == "function" || e.$$typeof !== void 0 || e.__v_isVNode !== void 0 || e._isVNode !== void 0 || e.isJSX !== void 0) return !1;
	let t = Object.getPrototypeOf(e);
	return t === Object.prototype || t === null || Array.isArray(e);
}, x = (e, t) => {
	if (e === void 0) return t;
	if (t === void 0 || Array.isArray(e)) return e;
	if (b(e) && b(t)) {
		let n = { ...e };
		for (let r of Object.keys(t)) r === "__proto__" || r === "constructor" || t[r] === void 0 || (n[r] = e[r] === void 0 ? t[r] : x(e[r], t[r]));
		return n;
	}
	return e;
}, S = (e, t, n) => {
	let r = (t) => e[t], i = /* @__PURE__ */ new Set(), a = [], o = (e) => {
		e && !i.has(e) && (i.add(e), a.push(e));
	};
	o(t), t.includes("-") && o(t.split("-")[0]), o(n), n?.includes("-") && o(n.split("-")[0]);
	let s = [];
	for (let e of a) {
		let t = r(e);
		if (t !== void 0) {
			if (typeof t == "string") {
				if (s.length === 0) return t;
				continue;
			}
			s.push(t);
		}
	}
	if (s.length !== 0) return s.length === 1 || Array.isArray(s[0]) ? s[0] : s.reduce((e, t) => x(e, t));
}, C = process.env.INTLAYER_NODE_TYPE_TRANSLATION === "false", w = process.env.INTLAYER_NODE_TYPE_INSERTION === "false", T = {
	id: "fallback-plugin",
	canHandle: () => !1,
	transform: (e) => e
}, E = (e, t) => C ? T : {
	id: "translation-plugin",
	canHandle: (e) => typeof e == "object" && e?.nodeType === "translation",
	transform: (n, r, i) => {
		let a = { ...n.translation ?? {} };
		for (let e in a) {
			let t = {
				...r,
				children: a[e],
				keyPath: [...r.keyPath, {
					type: te,
					key: e
				}]
			};
			a[e] = i(a[e], t);
		}
		return S(a, e, t);
	}
}, D = T, O = T, ie = w ? T : {
	id: "insertion-plugin",
	canHandle: (e) => typeof e == "object" && e?.nodeType === "insertion",
	transform: (e, t, n) => {
		let r = [...t.keyPath, { type: _ }], i = e[_], a = {
			id: "insertion-string-plugin",
			canHandle: (e) => typeof e == "string",
			transform: (e, n, r) => {
				let i = r(e, {
					...n,
					children: e,
					plugins: [...(t.plugins ?? []).filter((e) => e.id !== "intlayer-node-plugin")]
				});
				return (e) => {
					let a = re(i, e);
					return r(a, {
						...n,
						plugins: t.plugins,
						children: a
					});
				};
			}
		};
		return n(i, {
			...t,
			children: i,
			keyPath: r,
			plugins: [a, ...t.plugins ?? []]
		});
	}
}, k = T, A = (e) => T, j = T, M = (e, t = !0) => [
	E(e ?? p.defaultLocale, t ? p.defaultLocale : void 0),
	D,
	O,
	ie,
	A(e ?? p.defaultLocale),
	j,
	k
].filter(Boolean), N = (e, t, n = []) => y(e, {
	...t,
	plugins: n
}), P = (e, t, n = M(t)) => {
	let r = {
		dictionaryKey: e.key,
		dictionaryPath: e.filePath,
		keyPath: [],
		plugins: n
	};
	return N(e.content, r, n);
}, F = (e) => e != null && typeof e != "string" && typeof e != "number" && typeof e != "boolean", I = /\{\{\s*(.*?)\s*\}\}/g, L = (e, t = {}) => {
	if (!Object.values(t).some(F)) return {
		isSimple: !0,
		parts: e.replace(I, (e, n) => (t[n.trim()] ?? "").toString())
	};
	let n = e.split(I), r = [];
	for (let e = 0; e < n.length; e++) if (e % 2 == 0) n[e] && r.push(n[e]);
	else {
		let i = t[n[e].trim()];
		i != null && r.push(i);
	}
	return {
		isSimple: !1,
		parts: r
	};
}, R = process.env.INTLAYER_NODE_TYPE_INTLAYER_NODE === "false", z = process.env.INTLAYER_NODE_TYPE_REACT_NODE === "false", B = process.env.INTLAYER_NODE_TYPE_INSERTION === "false";
i(() => import("./MarkdownRendererPlugin-CtgvytJV.js").then((e) => ({ default: e.MarkdownRendererPlugin }))), i(() => import("./HTMLRendererPlugin-CAjFLd8d.js").then((e) => ({ default: e.HTMLRendererPlugin })));
var V = R ? T : {
	id: "intlayer-node-plugin",
	canHandle: (e) => typeof e == "bigint" || typeof e == "string" || typeof e == "number",
	transform: (e, { plugins: t, ...n }) => h({
		...n,
		value: n.children,
		children: n.children
	})
}, H = z ? T : {
	id: "react-node-plugin",
	canHandle: (e) => typeof e == "object" && e?.props !== void 0 && e.key !== void 0,
	transform: (e, { plugins: t, ...n }) => h({
		...n,
		value: "[[react-element]]",
		children: g(e)
	})
}, U = (t, r) => {
	let i = L(t, r);
	return i.isSimple ? i.parts : n(e, null, ...i.parts.map((t, r) => n(e, { key: r }, t)));
}, W = B ? T : {
	id: "insertion-plugin",
	canHandle: (e) => typeof e == "object" && e?.nodeType === "insertion",
	transform: (e, t, n) => {
		let r = [...t.keyPath, { type: _ }], i = e[_], a = {
			id: "insertion-string-plugin",
			canHandle: (e) => typeof e == "string",
			transform: (e, n, r) => {
				let i = r(e, {
					...n,
					children: e,
					plugins: [...(t.plugins ?? []).filter((e) => e.id !== "intlayer-node-plugin")]
				});
				return (e) => {
					let a = U(i, e);
					return r(a, {
						...n,
						plugins: t.plugins,
						children: a
					});
				};
			}
		}, o = n(i, {
			...t,
			children: i,
			keyPath: r,
			plugins: [a, ...t.plugins ?? []]
		});
		return typeof i == "object" && i && "nodeType" in i && ["enumeration", "condition"].includes(i.nodeType) ? (e) => (t) => {
			let n = o(t);
			return typeof n == "function" ? n(e) : n;
		} : o;
	}
}, ae = T, G = T, K = (e, t = !0) => [
	E(e ?? p.defaultLocale, t ? p.defaultLocale : void 0),
	D,
	O,
	A(e ?? p.defaultLocale),
	j,
	k,
	V,
	H,
	W,
	ae,
	G
].filter(Boolean), q = (e, t) => P(e, t, K(t)), J = (e, t = p?.locales, n = p?.defaultLocale) => {
	let r = [e].flat(), i = (e) => e.trim().toLowerCase();
	try {
		for (let e of r) {
			let n = i(e), r = t.find((e) => i(e) === n);
			if (r) return r;
			let [a] = n.split("-"), o = t.find((e) => i(e).split("-")[0] === a);
			if (o) return o;
		}
	} catch {}
	return n;
}, Y = process.env.INTLAYER_ROUTING_STORAGE_COOKIES === "false";
process.env.INTLAYER_ROUTING_STORAGE_HEADERS;
var oe = (e, t, n) => {
	let r = [`${e}=${encodeURIComponent(t)}`];
	return n.path && r.push(`Path=${n.path}`), n.domain && r.push(`Domain=${n.domain}`), n.expires instanceof Date && r.push(`Expires=${n.expires.toUTCString()}`), n.secure && r.push("Secure"), n.sameSite && r.push(`SameSite=${n.sameSite}`), r.join("; ");
}, se = (e) => {
	let { locales: t } = p;
	if (e?.isCookieEnabled === !1) return;
	let n = (e) => !!e && t.includes(e);
	if (!Y) for (let t = 0; t < (m.storage.cookies ?? []).length; t++) try {
		let r = e?.getCookie?.(m.storage.cookies[t].name);
		if (n(r)) return r;
	} catch {}
}, ce = (e, t) => {
	if (t?.isCookieEnabled !== !1 && !Y && m.storage.cookies) for (let n = 0; n < m.storage.cookies.length; n++) {
		let { name: r, attributes: i } = m.storage.cookies[n];
		try {
			t?.setCookieStore && t.setCookieStore(r, e, {
				...i,
				expires: i.expires instanceof Date ? i.expires.getTime() : i.expires
			});
		} catch {
			try {
				t?.setCookieString && t.setCookieString(r, oe(r, e, i));
			} catch {}
		}
	}
}, X = {
	getCookie: (e) => document.cookie.split(";").find((t) => t.trim().startsWith(`${e}=`))?.split("=")[1],
	getLocaleStorage: (e) => localStorage.getItem(e),
	getSessionStorage: (e) => sessionStorage.getItem(e),
	isCookieEnabled: !0,
	setCookieStore: (e, t, n) => cookieStore.set({
		name: e,
		value: t,
		path: n.path,
		domain: n.domain,
		expires: n.expires,
		sameSite: n.sameSite
	}),
	setCookieString: (e, t) => {
		document.cookie = t;
	},
	setSessionStorage: (e, t) => sessionStorage.setItem(e, t),
	setLocaleStorage: (e, t) => localStorage.setItem(e, t)
}, Z = se(X), le = (e, t) => ce(e, {
	...X,
	isCookieEnabled: t
}), ue = () => {
	let { locale: e } = a(Q) ?? {}, t = c(null);
	o(() => {}, []), o(() => {
		!e || !t.current || t.current.currentLocale.set(e);
	}, [e]);
}, de = ({ children: e }) => (ue(), e), fe = () => {
	typeof window < "u" && (window.intlayer = { enabled: !0 });
}, Q = t({
	locale: Z ?? p?.defaultLocale,
	setLocale: () => null,
	isCookieEnabled: !0
}), pe = ({ locale: e, defaultLocale: t, children: n, setLocale: r, disableEditor: i, isCookieEnabled: a }) => {
	let { locales: s, defaultLocale: c } = p ?? {}, [l, d] = ee(e ?? Z ?? t ?? c);
	o(() => {
		e && e !== l && d(e);
	}, [e]), o(() => {
		fe();
	}, []);
	let f = r ?? ((e) => {
		if (l.toString() !== e.toString()) {
			if (!s?.map(String).includes(e)) {
				console.error(`Locale ${e} is not available`);
				return;
			}
			d(e), le(e, a);
		}
	}), m = J(l);
	return /* @__PURE__ */ u(Q.Provider, {
		value: {
			locale: m,
			setLocale: f,
			disableEditor: i
		},
		children: n
	});
}, $ = ({ children: e, ...t }) => /* @__PURE__ */ d(pe, {
	...t,
	children: [/* @__PURE__ */ u(de, {}), e]
}), me = (e, t) => {
	let { locale: n } = a(Q) ?? {};
	return s(() => q(e, t ?? n), [
		e.key,
		n,
		t
	]);
};
//#endregion
//#region src/components/pages/pricing/PricingTiers.tsx
function he() {
	let e = me(f);
	return /* @__PURE__ */ u("div", {
		className: "grid gap-6 md:grid-cols-3",
		children: [
			{
				name: e.y,
				price: e.r,
				period: e.l,
				features: [
					e.c({ runs: "5" }),
					e.o({ libs: "3" }),
					e.e,
					e.w
				]
			},
			{
				name: e.v,
				price: e.s,
				period: e.p,
				features: [
					e.aa,
					e.a,
					e.t,
					e.u,
					e.d,
					e.n
				],
				highlighted: !0
			},
			{
				name: e.j,
				price: e.g,
				period: "",
				features: [
					e.k,
					e.q,
					e.x,
					e.i,
					e.h,
					e.b,
					e.z
				]
			}
		].map((t) => /* @__PURE__ */ d("div", {
			className: `flex flex-col rounded-lg border p-6 ${t.highlighted ? "border-primary bg-primary/5 ring-1 ring-primary" : "border-border bg-card"}`,
			children: [
				/* @__PURE__ */ u("h3", {
					className: "text-lg font-semibold text-foreground",
					children: t.name
				}),
				/* @__PURE__ */ d("div", {
					className: "my-4",
					children: [/* @__PURE__ */ u("span", {
						className: "text-3xl font-bold text-foreground",
						children: t.price
					}), /* @__PURE__ */ u("span", {
						className: "text-sm text-muted-foreground",
						children: t.period
					})]
				}),
				/* @__PURE__ */ u("ul", {
					className: "mb-6 flex-1 space-y-2",
					children: t.features.map((e, t) => /* @__PURE__ */ d("li", {
						className: "flex items-center gap-2 text-sm text-muted-foreground",
						children: [
							/* @__PURE__ */ u("span", {
								className: "text-primary",
								children: "✓"
							}),
							" ",
							e
						]
					}, t))
				}),
				/* @__PURE__ */ u("button", {
					type: "button",
					className: `w-full rounded-md px-4 py-2 text-sm font-medium transition-opacity hover:opacity-90 ${t.highlighted ? "bg-primary text-primary-foreground" : "border border-border text-foreground hover:bg-accent"}`,
					children: t.name === e.j ? e.f : e.m
				})
			]
		}, t.name.value))
	});
}
//#endregion
//#region scripts/Wrapper.tsx
function ge({ children: e }) {
	return /* @__PURE__ */ u($, {
		locale: "en",
		children: e
	});
}
//#endregion
//#region src/components/pages/pricing/PricingTiers.wrapper.tsx
function _e() {
	return /* @__PURE__ */ u(ge, { children: /* @__PURE__ */ u(he, {}) });
}
//#endregion
export { _e as default };
import { Fragment as e, createContext as t, createElement as n, useContext as r } from "react";
import { jsx as i } from "react/jsx-runtime";
//#region ../../node_modules/.bun/@intlayer+core@8.7.0-canary.0+3f10a4be4e334a9b/node_modules/@intlayer/core/dist/esm/interpreter/getHTML.mjs
var a = (e) => {
	let t = {}, n = /([a-zA-Z0-9-]+)="([^"]*)"/g, r = n.exec(e);
	for (; r !== null;) t[r[1]] = r[2], r = n.exec(e);
	return t;
}, o = /* @__PURE__ */ new Map(), s = (e) => {
	if (o.has(e)) return o.get(e);
	if (typeof e != "string") return [];
	let t = /<(\/)?([a-zA-Z0-9.-]+)([\s\S]*?)(\/?)>/g, n = [], r = [], i = 0, s = t.exec(e), c = (e) => {
		(r.length > 0 ? r[r.length - 1].children : n).push(e);
	};
	for (; s !== null;) {
		let [n, o, l, u, d] = s, f = s.index;
		f > i && c(e.slice(i, f));
		let p = o === "/", m = d === "/" || u.trim().endsWith("/") || n.endsWith("/>"), h = u.trim().replace(/\/$/, "").trim();
		if (p) {
			let e = r[r.length - 1];
			if (e && e.tagName === l) {
				let e = r.pop();
				e && c({
					tagName: e.tagName,
					props: e.props,
					children: e.children
				});
			}
		} else if (m) c({
			tagName: l,
			props: a(h),
			children: []
		});
		else {
			let e = a(h);
			r.push({
				tagName: l,
				children: [],
				props: e
			});
		}
		i = f + n.length, s = t.exec(e);
	}
	for (i < e.length && c(e.slice(i)); r.length > 0;) {
		let e = r.pop();
		e && c({
			tagName: e.tagName,
			props: e.props,
			children: e.children
		});
	}
	return o.set(e, n), n;
}, c = (e, t) => {
	let n = s(e), r = 0, i = (e) => {
		if (typeof e == "string") return e;
		let { tagName: n, props: a, children: o } = e, s = o.flatMap(i), c = r++, l = t[n];
		if (!l) {
			let e = n.toLowerCase(), r = Object.keys(t).find((t) => t.toLowerCase() === e);
			r && (l = t[r]);
		}
		let u = `html-tag-${n}-${c}`;
		if (typeof l == "function") return l({
			...a,
			children: s,
			key: u
		});
		if (typeof l == "string") {
			let e = t[l];
			return typeof e == "function" ? e({
				...a,
				children: s,
				key: u
			}) : s;
		}
		if (typeof l == "object" && l && "tag" in l) {
			let { tag: e, props: n } = l, r = t[e];
			return typeof r == "function" ? r({
				...a,
				...n,
				children: s,
				key: u
			}) : s;
		}
		return s;
	}, a = n.flatMap(i);
	return a.length === 1 ? a[0] : a;
}, l = t(void 0), u = () => r(l), d = (t, { components: r = {} } = {}) => {
	let a = Object.fromEntries(Object.entries(r).filter(([, e]) => e).map(([e, t]) => [e, (e) => n(t, e)]));
	return /* @__PURE__ */ i(e, { children: c(t, new Proxy(a, { get(e, t) {
		if (typeof t == "string" && t in e) return e[t];
		if (typeof t == "string" && /^[a-z][a-z0-9]*$/.test(t)) return (e) => n(t, e);
	} })) });
}, f = (e) => {
	let { html: t, userComponents: n } = e;
	return d(t, { components: {
		...u()?.components,
		...n
	} });
};
//#endregion
export { f as HTMLRendererPlugin };
import { createContext as e, useContext as t } from "react";
import "react/jsx-runtime";
//#region ../../node_modules/.bun/react-intlayer@8.7.0-canary.0+21ccd8898788a04d/node_modules/react-intlayer/dist/esm/markdown/MarkdownProvider.mjs
var n = e(void 0), r = () => t(n), i = (e) => {
	let { children: t, options: n, components: i } = e, a = r();
	return (a?.renderMarkdown ?? ((e) => e))(t, n, {
		...a?.components ?? {},
		...i ?? {}
	});
};
//#endregion
export { i as MarkdownRendererPlugin };

// results/vite-solid-intlayer-static/bundle/pages/PricingTiers_min.js
import { Dynamic as e, className as t, createComponent as n, effect as r, insert as i, memo as a, template as o } from "solid-js/web";
import { For as s, createContext as c, createMemo as l, useContext as u } from "solid-js";
var d = {
	key: "pricing-tiers",
	content: {
		nodeType: "translation",
		translation: {
			en: {
				u: "Starter",
				x: "5 benchmark runs/day",
				f: "Community support",
				s: "Public results",
				r: "Pro",
				w: "Unlimited runs",
				a: "All libraries",
				p: "Priority support",
				q: "Private results",
				e: "CI integration",
				n: "Historical data",
				k: "Enterprise",
				h: "Custom",
				l: "Everything in Pro",
				o: "On-premise option",
				t: "SSO & SAML",
				j: "Dedicated account manager",
				i: "Custom SLAs",
				b: "Audit logs",
				v: "Training sessions",
				d: "border-primary bg-primary/5 ring-1 ring-primary",
				c: "border border-border text-foreground hover:bg-accent",
				g: "Contact Sales",
				m: "Get Started"
			},
			fr: {
				u: "Débutant",
				x: "5 exécutions de benchmark/jour",
				f: "Support communautaire",
				s: "Résultats publics",
				r: "Pro",
				w: "Exécutions illimitées",
				a: "Toutes les bibliothèques",
				p: "Support prioritaire",
				q: "Résultats privés",
				e: "Intégration CI",
				n: "Données historiques",
				k: "Entreprise",
				h: "Personnalisé",
				l: "Tout ce qui est dans Pro",
				o: "Option sur site",
				t: "SSO et SAML",
				j: "Gestionnaire de compte dédié",
				i: "SLA personnalisés",
				b: "Logs d'audit",
				v: "Sessions de formation",
				d: "border-primary bg-primary/5 ring-1 ring-primary",
				c: "border border-border text-foreground hover:bg-accent",
				g: "Contacter le service commercial",
				m: "Démarrer"
			},
			es: {
				u: "Starter",
				x: "5 ejecuciones de benchmark al día",
				f: "Soporte de la comunidad",
				s: "Resultados públicos",
				r: "Pro",
				w: "Ejecuciones ilimitadas",
				a: "Todas las bibliotecas",
				p: "Soporte prioritario",
				q: "Resultados privados",
				e: "Integración de CI",
				n: "Datos históricos",
				k: "Enterprise",
				h: "Personalizado",
				l: "Todo en Pro",
				o: "Opción on-premise",
				t: "SSO y SAML",
				j: "Gestor de cuentas dedicado",
				i: "SLAs personalizados",
				b: "Registros de auditoría",
				v: "Sesiones de formación",
				d: "border-primary bg-primary/5 ring-1 ring-primary",
				c: "border border-border text-foreground hover:bg-accent",
				g: "Contactar con ventas",
				m: "Empezar"
			},
			de: {
				u: "Starter",
				x: "5 Benchmark-Läufe/Tag",
				f: "Community-Support",
				s: "Öffentliche Ergebnisse",
				r: "Pro",
				w: "Unbegrenzte Läufe",
				a: "Alle Bibliotheken",
				p: "Prioritäts-Support",
				q: "Private Ergebnisse",
				e: "CI-Integration",
				n: "Historische Daten",
				k: "Enterprise",
				h: "Benutzerdefiniert",
				l: "Alles in Pro",
				o: "On-Premise-Option",
				t: "SSO & SAML",
				j: "Dedizierter Account Manager",
				i: "Benutzerdefinierte SLAs",
				b: "Audit-Protokolle",
				v: "Schulungen",
				d: "border-primary bg-primary/5 ring-1 ring-primary",
				c: "border border-border text-foreground hover:bg-accent",
				g: "Vertrieb kontaktieren",
				m: "Erste Schritte"
			},
			it: {
				u: "Starter",
				x: "5 esecuzioni di benchmark al giorno",
				f: "Supporto della comunità",
				s: "Risultati pubblici",
				r: "Pro",
				w: "Esecuzioni illimitate",
				a: "Tutte le librerie",
				p: "Supporto prioritario",
				q: "Risultati privati",
				e: "Integrazione CI",
				n: "Dati storici",
				k: "Enterprise",
				h: "Personalizzato",
				l: "Tutto quello che c'è in Pro",
				o: "Opzione on-premise",
				t: "SSO e SAML",
				j: "Account manager dedicato",
				i: "SLA personalizzati",
				b: "Log di audit",
				v: "Sessioni di formazione",
				d: "border-primary bg-primary/5 ring-1 ring-primary",
				c: "border border-border text-foreground hover:bg-accent",
				g: "Contatta l'ufficio vendite",
				m: "Inizia subito"
			},
			pt: {
				u: "Starter",
				x: "5 execuções de benchmark/dia",
				f: "Suporte da comunidade",
				s: "Resultados públicos",
				r: "Pro",
				w: "Execuções ilimitadas",
				a: "Todas as biblioteche",
				p: "Suporte prioritário",
				q: "Resultados privados",
				e: "Integração CI",
				n: "Dados históricos",
				k: "Enterprise",
				h: "Personalizado",
				l: "Tudo no Pro",
				o: "Opção on-premise",
				t: "SSO e SAML",
				j: "Gerente de conta dedicado",
				i: "SLAs personalizados",
				b: "Logs de auditoria",
				v: "Sessões de treinamento",
				d: "border-primary bg-primary/5 ring-1 ring-primary",
				c: "border border-border text-foreground hover:bg-accent",
				g: "Contatar Vendas",
				m: "Começar"
			},
			zh: {
				u: "入门版",
				x: "每天 5 次基准测试运行",
				f: "社区支持",
				s: "公开结果",
				r: "专业版",
				w: "无限次运行",
				a: "所有库",
				p: "优先支持",
				q: "私人结果",
				e: "CI 集成",
				n: "历史数据",
				k: "企业版",
				h: "自定义",
				l: "包含专业版所有功能",
				o: "本地部署选项",
				t: "SSO 和 SAML",
				j: "专属客户经理",
				i: "自定义 SLA",
				b: "审核日志",
				v: "培训课程",
				d: "border-primary bg-primary/5 ring-1 ring-primary",
				c: "border border-border text-foreground hover:bg-accent",
				g: "联系销售",
				m: "开始使用"
			},
			ja: {
				u: "スターター",
				x: "1日5回のベンチマーク実行",
				f: "コミュニティサポート",
				s: "公開結果",
				r: "プロ",
				w: "実行無制限",
				a: "すべてのライブラリ",
				p: "優先サポート",
				q: "プライベートな結果",
				e: "CI 統合",
				n: "履歴データ",
				k: "エンタープライズ",
				h: "カスタム",
				l: "プロのすべての機能",
				o: "オンプレミスオプション",
				t: "SSO と SAML",
				j: "専任のアカウントマネージャー",
				i: "カスタムSLA",
				b: "監査ログ",
				v: "トレーニングセッション",
				d: "border-primary bg-primary/5 ring-1 ring-primary",
				c: "border border-border text-foreground hover:bg-accent",
				g: "営業に連絡",
				m: "始める"
			},
			ko: {
				u: "스타터",
				x: "일일 5회 벤치마크 실행",
				f: "커뮤니티 지원",
				s: "공개 결과",
				r: "프로",
				w: "무제한 실행",
				a: "모든 라이브러리",
				p: "우선 지원",
				q: "비공개 결과",
				e: "CI 통합",
				n: "기록 데이터",
				k: "엔터프라이즈",
				h: "커스텀",
				l: "Pro의 모든 기능 포함",
				o: "온프레미스 옵션",
				t: "SSO 및 SAML",
				j: "전담 어카운트 매니저",
				i: "맞춤형 SLA",
				b: "감사 로그",
				v: "교육 세션",
				d: "border-primary bg-primary/5 ring-1 ring-primary",
				c: "border border-border text-foreground hover:bg-accent",
				g: "영업팀 문의",
				m: "시작하기"
			},
			ru: {
				u: "Стартовый",
				x: "5 запусков бенчмарка в день",
				f: "Поддержка сообщества",
				s: "Публичные результаты",
				r: "Профи",
				w: "Безлимитные запуски",
				a: "Все библиотеки",
				p: "Приоритетная поддержка",
				q: "Приватные результаты",
				e: "Интеграция с CI",
				n: "Исторические данные",
				k: "Корпоративный",
				h: "Индивидуальный",
				l: "Все, что в Профи",
				o: "Локальная установка",
				t: "SSO и SAML",
				j: "Выделенный менеджер",
				i: "Индивидуальные SLA",
				b: "Журналы аудита",
				v: "Обучающие сессии",
				d: "border-primary bg-primary/5 ring-1 ring-primary",
				c: "border border-border text-foreground hover:bg-accent",
				g: "Связаться с отделом продаж",
				m: "Начать"
			}
		}
	}
}, f = ({ children: e, value: t, additionalProps: n }) => {
	let r = [e];
	if (r.value = t, n) for (let e in n) r[e] = n[e];
	return new Proxy(r, { get(e, n, r) {
		return n === "value" ? t : n === "toString" ? () => String(t) : n === Symbol.toPrimitive ? (e) => e === "string" ? String(t) : e === "number" ? Number(t) : t : Reflect.get(e, n, r);
	} });
}, p = (t) => {
	if (typeof t == "string") return t;
	let { type: n, props: r } = ((e) => {
		if (e?.props && typeof e.props.children == "object") {
			let t = [], { children: n } = e.props;
			return Object.keys(n ?? {}).forEach((e) => {
				t.push(p(n?.[e]));
			}), {
				...e,
				props: {
					...e.props,
					children: t
				}
			};
		}
		return {
			...e,
			props: {
				...e.props,
				children: e.props?.children ?? []
			}
		};
	})(t);
	return e({
		component: n ?? "span",
		...r,
		children: r.children
	});
}, m = {
	locales: [
		"en",
		"fr",
		"es",
		"de",
		"it",
		"pt",
		"zh",
		"ja",
		"ko",
		"ru"
	],
	requiredLocales: [
		"en",
		"fr",
		"es",
		"de",
		"it",
		"pt",
		"zh",
		"ja",
		"ko",
		"ru"
	],
	strictMode: "inclusive",
	defaultLocale: "en"
}, h = {
	mode: "prefix-all",
	storage: {
		cookies: [{
			name: "INTLAYER_LOCALE",
			attributes: {}
		}],
		headers: [{ name: "x-intlayer-locale" }]
	},
	basePath: ""
}, g = "translation", _ = "object", v = "array", y = (e, t) => {
	for (let n of t.plugins ?? []) if (n.canHandle(e)) return n.transform(e, t, (e, t) => y(e, t));
	if (typeof e != "object" || !e || e.$$typeof !== void 0 || e.__v_isVNode !== void 0 || e._isVNode !== void 0 || e.isJSX !== void 0 || typeof e == "function") return e;
	if (Array.isArray(e)) return e.map((e, n) => y(e, {
		...t,
		children: e,
		keyPath: [...t.keyPath, {
			type: v,
			key: n
		}]
	}));
	let n = {};
	for (let r in e) Object.defineProperty(n, r, {
		enumerable: !0,
		configurable: !0,
		get: function() {
			let n = {
				...t,
				children: e[r],
				keyPath: [...t.keyPath, {
					type: _,
					key: r
				}]
			}, i = y(e[r], n);
			return Object.defineProperty(this, r, {
				value: i,
				enumerable: !0,
				configurable: !0
			}), i;
		}
	});
	return n;
}, b = (e) => {
	if (typeof e != "object" || !e || typeof e.then == "function" || e.$$typeof !== void 0 || e.__v_isVNode !== void 0 || e._isVNode !== void 0 || e.isJSX !== void 0) return !1;
	let t = Object.getPrototypeOf(e);
	return t === Object.prototype || t === null || Array.isArray(e);
}, x = (e, t) => {
	if (e === void 0) return t;
	if (t === void 0 || Array.isArray(e)) return e;
	if (b(e) && b(t)) {
		let n = { ...e };
		for (let r of Object.keys(t)) r === "__proto__" || r === "constructor" || t[r] === void 0 || (n[r] = e[r] === void 0 ? t[r] : x(e[r], t[r]));
		return n;
	}
	return e;
}, S = (e, t, n) => {
	let r = (t) => e[t], i = /* @__PURE__ */ new Set(), a = [], o = (e) => {
		e && !i.has(e) && (i.add(e), a.push(e));
	};
	o(t), t.includes("-") && o(t.split("-")[0]), o(n), n?.includes("-") && o(n.split("-")[0]);
	let s = [];
	for (let e of a) {
		let t = r(e);
		if (t !== void 0) {
			if (typeof t == "string") {
				if (s.length === 0) return t;
				continue;
			}
			s.push(t);
		}
	}
	if (s.length !== 0) return s.length === 1 || Array.isArray(s[0]) ? s[0] : s.reduce((e, t) => x(e, t));
}, C = {
	id: "fallback-plugin",
	canHandle: () => !1,
	transform: (e) => e
}, w = (e, t) => process.env.INTLAYER_NODE_TYPE_TRANSLATION === "false" ? C : {
	id: "translation-plugin",
	canHandle: (e) => typeof e == "object" && e?.nodeType === "translation",
	transform: (n, r, i) => {
		let a = n.translation ?? {}, o = {};
		for (let e in a) {
			let t = {
				...r,
				children: a[e],
				keyPath: [...r.keyPath, {
					type: g,
					key: e
				}]
			};
			o[e] = i(a[e], t);
		}
		return S(o, e, t);
	}
}, T = C, E = C, D = C, O = C, k = (e) => C, A = C, j = (e, t = !0) => [
	w(e ?? m.defaultLocale, t ? m.defaultLocale : void 0),
	T,
	E,
	D,
	k(e ?? m.defaultLocale),
	A,
	O
], M = (e, t, n = []) => y(e, {
	...t,
	plugins: n
}), N = (e, t, n = j(t)) => {
	let r = {
		dictionaryKey: e.key,
		dictionaryPath: e.filePath,
		keyPath: [],
		plugins: n
	};
	return M(e.content, r, n);
}, P = {
	id: "intlayer-node-plugin",
	canHandle: (e) => typeof e == "bigint" || typeof e == "string" || typeof e == "number",
	transform: (e, { plugins: t, ...n }) => f({
		...n,
		value: n.children,
		children: n.children
	})
}, F = process.env.INTLAYER_NODE_TYPE_SOLID_NODE === "false" ? C : {
	id: "solid-node-plugin",
	canHandle: (e) => typeof e == "object" && e?.props !== void 0 || typeof Node < "u" && e instanceof Node,
	transform: (e, { plugins: t, ...n }) => f({
		...n,
		value: "[[solid-element]]",
		children: typeof Node < "u" && e instanceof Node ? e : p(e)
	})
}, I = C, L = C, R = C, z = /* @__PURE__ */ new Map(), B = (e, t = !0) => {
	let n = `${e ?? m.defaultLocale}_${t}`;
	if (z.has(n)) return z.get(n);
	let r = [
		w(e ?? m.defaultLocale, t ? m.defaultLocale : void 0),
		T,
		E,
		k(e ?? m.defaultLocale),
		A,
		O,
		P,
		F,
		I,
		L,
		R
	];
	return z.set(n, r), r;
}, V = (e, t) => N(e, t, B(t)), H = process.env.INTLAYER_ROUTING_STORAGE_COOKIES === "false";
process.env.INTLAYER_ROUTING_STORAGE_HEADERS;
var U = (e = W) => {
	let { locales: t } = m;
	if (e?.isCookieEnabled === !1) return;
	let n = (e) => !!e && t.includes(e);
	if (!H) for (let t = 0; t < (h.storage.cookies ?? []).length; t++) try {
		let r = e?.getCookie?.(h.storage.cookies[t].name);
		if (n(r)) return r;
	} catch {}
}, W = {
	getCookie: (e) => document.cookie.split(";").find((t) => t.trim().startsWith(`${e}=`))?.split("=")[1],
	getLocaleStorage: (e) => localStorage.getItem(e),
	getSessionStorage: (e) => sessionStorage.getItem(e),
	isCookieEnabled: !0,
	setCookieStore: (e, t, n) => cookieStore.set({
		name: e,
		value: t,
		path: n.path,
		domain: n.domain,
		expires: n.expires,
		sameSite: n.sameSite
	}),
	setCookieString: (e, t) => {
		document.cookie = t;
	},
	setSessionStorage: (e, t) => sessionStorage.setItem(e, t),
	setLocaleStorage: (e, t) => localStorage.setItem(e, t)
}, G = U(W), K = c({
	locale: () => G ?? m?.defaultLocale,
	setLocale: () => null
}), q = (e, t) => {
	let n = u(K) ?? {};
	return l(() => V(e, t ?? n?.locale?.()));
}, J = o("<div class=\"grid gap-6 md:grid-cols-3\">"), Y = o("<div><h3 class=\"text-lg font-semibold text-foreground\"></h3><div class=my-4><span class=\"text-3xl font-bold text-foreground\"></span><span class=\"text-sm text-muted-foreground\"></span></div><ul class=\"mb-6 flex-1 space-y-2\"></ul><button type=button>"), X = o("<li class=\"flex items-center gap-2 text-sm text-muted-foreground\"><span class=text-primary>✓</span> ");
function Z() {
	let e = q(d), o = [
		{
			name: e().starter.value,
			price: "$0",
			period: "forever",
			features: [
				e().x5BenchmarkRunsday.value,
				"3 libraries",
				e().communitySupport.value,
				e().publicResults.value
			]
		},
		{
			name: e().pro.value,
			price: "$29",
			period: "/month",
			features: [
				e().unlimitedRuns.value,
				e().allLibraries.value,
				e().prioritySupport.value,
				e().privateResults.value,
				e().ciIntegration.value,
				e().historicalData.value
			],
			highlighted: !0
		},
		{
			name: e().enterprise.value,
			price: e().custom.value,
			period: "",
			features: [
				e().everythingInPro.value,
				e().onPremiseOption.value,
				e().ssoSaml.value,
				e().dedicatedAccountManager.value,
				e().customSlas.value,
				e().auditLogs.value,
				e().trainingSessions.value
			]
		}
	];
	return (() => {
		var c = J();
		return i(c, n(s, {
			each: o,
			children: (o) => (() => {
				var c = Y(), l = c.firstChild, u = l.nextSibling, d = u.firstChild, f = d.nextSibling, p = u.nextSibling, m = p.nextSibling;
				return i(l, () => o.name), i(d, () => o.price), i(f, () => o.period), i(p, n(s, {
					get each() {
						return o.features;
					},
					children: (e) => (() => {
						var t = X();
						return t.firstChild.nextSibling, i(t, e, null), t;
					})()
				})), i(m, (() => {
					var t = a(() => o.name === e().enterprise.value);
					return () => t() ? e().contactSales.value : e().getStarted.value;
				})()), r((n) => {
					var r = `flex flex-col rounded-lg border p-6 ${o.highlighted ? e().borderPrimaryBgPrimary5Ring.value : "border-border bg-card"}`, i = `w-full rounded-md px-4 py-2 text-sm font-medium transition-opacity hover:opacity-90 ${o.highlighted ? "bg-primary text-primary-foreground" : e().borderBorderBorderTextForeground.value}`;
					return r !== n.e && t(c, n.e = r), i !== n.t && t(m, n.t = i), n;
				}, {
					e: void 0,
					t: void 0
				}), c;
			})()
		})), c;
	})();
}
export { Z as default };
