// apps-benchmark/vite-solid-dynamic/solid-intlayer-app/src/components/pages/products/ProductsGrid.tsx
import { useIntlayer } from 'solid-intlayer';
import { For } from 'solid-js';

export default function ProductsGrid() {
  const content = useIntlayer('products-grid');

  const products = [
    {
      name: content().benchmarkCli.value,
      desc: content().runBenchmarksLocallyFromYour.value,
      price: content().free.value,
    },
    {
      name: content().benchmarkCloud.value,
      desc: content().automatedCloudBasedBenchmarkingWith.value,
      price: '$29/mo',
    },
    {
      name: content().benchmarkEnterprise.value,
      desc: content().onPremiseDeploymentWithSso.value,
      price: content().contactUs.value,
    },
    {
      name: content().migrationAssistant.value,
      desc: content().aiPoweredToolThatHelps.value,
      price: '$99 one-time',
    },
    {
      name: content().translationQa.value,
      desc: content().automatedQualityChecksForMissing.value,
      price: '$19/mo',
    },
    {
      name: content().bundleOptimizer.value,
      desc: content().analyzesAndOptimizesYourI18n.value,
      price: '$49/mo',
    },
  ];

  return (
    <div class="grid gap-6 md:grid-cols-2 lg:grid-cols-3">
      <For each={products}>
        {(p) => (
          <div class="flex flex-col justify-between rounded-lg border border-border bg-card p-6">
            <div>
              <h3 class="mb-2 text-lg font-semibold text-foreground">
                {p.name}
              </h3>
              <p class="mb-4 text-sm text-muted-foreground">{p.desc}</p>
            </div>
            <div class="flex items-center justify-between">
              <span class="text-sm font-bold text-primary">{p.price}</span>
              <button
                type="button"
                class="rounded-md bg-primary px-4 py-2 text-xs font-medium text-primary-foreground transition-opacity hover:opacity-90"
              >
                {content().learnMore}
              </button>
            </div>
          </div>
        )}
      </For>
    </div>
  );
}

// apps-benchmark/nextjs-dynamic/next-international-app/components/pages/products/ProductsGrid.tsx
"use client";

import { useI18n } from "../../../locales/client";

export default function ProductsGrid() {
  const t = useI18n();

  const products = [
    {
      name: t("products.products-grid.benchmarkCli"),
      desc: t("products.products-grid.runBenchmarksLocallyFromYour"),
      price: t("products.products-grid.free"),
    },
    {
      name: t("products.products-grid.benchmarkCloud"),
      desc: t("products.products-grid.automatedCloudBasedBenchmarkingWith"),
      price: t("products.products-grid.price29mo"),
    },
    {
      name: t("products.products-grid.benchmarkEnterprise"),
      desc: t("products.products-grid.onPremiseDeploymentWithSso"),
      price: t("products.products-grid.contactUs"),
    },
    {
      name: t("products.products-grid.migrationAssistant"),
      desc: t("products.products-grid.aiPoweredToolThatHelps"),
      price: t("products.products-grid.price99oneTime"),
    },
    {
      name: t("products.products-grid.translationQa"),
      desc: t("products.products-grid.automatedQualityChecksForMissing"),
      price: t("products.products-grid.price19mo"),
    },
    {
      name: t("products.products-grid.bundleOptimizer"),
      desc: t("products.products-grid.analyzesAndOptimizesYourI18n"),
      price: t("products.products-grid.price49mo"),
    },
  ];

  return (
    <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">
      {products.map((p) => (
        <div
          key={p.name}
          className="flex flex-col justify-between rounded-lg border border-border bg-card p-6"
        >
          <div>
            <h3 className="mb-2 text-lg font-semibold text-foreground">
              {p.name}
            </h3>
            <p className="mb-4 text-sm text-muted-foreground">{p.desc}</p>
          </div>
          <div className="flex items-center justify-between">
            <span className="text-sm font-bold text-primary">{p.price}</span>
            <button
              type="button"
              className="rounded-md bg-primary px-4 py-2 text-xs font-medium text-primary-foreground hover:opacity-90 transition-opacity"
            >
              {t("products.products-grid.learnMore")}
            </button>
          </div>
        </div>
      ))}
    </div>
  );
}
