// nextjs-static/paraglide-next-app/app/[locale]/contact/page.tsx
import { lazy, Suspense } from "react";

const ContactHeader = lazy(
  () => import("../../../components/pages/contact/ContactHeader"),
);
const ContactForm = lazy(
  () => import("../../../components/pages/contact/ContactForm"),
);

export default function Contact() {
  return (
    <div className="container py-16">
      <div className="mx-auto max-w-2xl">
        <Suspense fallback={<div className="h-48 animate-pulse bg-muted/20" />}>
          <ContactHeader />
        </Suspense>

        <Suspense fallback={<div className="h-96 animate-pulse bg-muted/20" />}>
          <ContactForm />
        </Suspense>
      </div>
    </div>
  );
}

// apps-benchmark/vite-solid-scoped-dynamic/i18next-app/src/pages/Contact.tsx
import { lazy, Suspense } from "solid-js";

const ContactHeader = lazy(
  () => import("../components/pages/contact/ContactHeader"),
);
const ContactForm = lazy(() => import("../components/pages/contact/ContactForm"));

export default function Contact() {
  return (
    <div class="container py-16">
      <div class="mx-auto max-w-2xl">
        <Suspense fallback={<div class="h-48 animate-pulse bg-muted/20" />}>
          <ContactHeader />
        </Suspense>

        <Suspense fallback={<div class="h-96 animate-pulse bg-muted/20" />}>
          <ContactForm />
        </Suspense>
      </div>
    </div>
  );
}
