// apps-benchmark/nextjs-static/next-intlayer-app/src/app/[locale]/pricing/page.tsx
import { Suspense } from "react";
import PricingHeader from "@/components/pages/pricing/PricingHeader";
import PricingTiers from "@/components/pages/pricing/PricingTiers";
import type { NextPageIntlayer } from "next-intlayer";

const Pricing: NextPageIntlayer = () => (
  <div className="container py-16">
    <Suspense fallback={<div className="h-48 animate-pulse bg-muted/20" />}>
      <PricingHeader />
    </Suspense>

    <Suspense fallback={<div className="h-96 animate-pulse bg-muted/20" />}>
      <PricingTiers />
    </Suspense>
  </div>
);

export default Pricing;

// apps-benchmark/vite-solid-scoped-dynamic/i18next-app/src/pages/Pricing.tsx
import { lazy, Suspense } from "solid-js";

const PricingHeader = lazy(
  () => import("../components/pages/pricing/PricingHeader"),
);
const PricingTiers = lazy(
  () => import("../components/pages/pricing/PricingTiers"),
);

export default function Pricing() {
  return (
    <div class="container py-16">
      <Suspense fallback={<div class="h-48 animate-pulse bg-muted/20" />}>
        <PricingHeader />
      </Suspense>

      <Suspense fallback={<div class="h-96 animate-pulse bg-muted/20" />}>
        <PricingTiers />
      </Suspense>
    </div>
  );
}
