// apps-benchmark/vite-solid-static/i18next-app/scripts/EmptyComponent.tsx
import i18next from "i18next";
import { createSignal } from "solid-js";

const i18n = i18next.createInstance();
i18n.init({
  lng: "en",
  fallbackLng: "en",
  resources: { en: { translation: {} } },
  interpolation: { escapeValue: false },
});

const [t] = createSignal(i18n.t.bind(i18n));

export default function EmptyComponent() {
  const value = t()("header.home");
  void value;
  return null;
}

// apps-benchmark/vite-react-static/react-i18next-app/scripts/EmptyComponent.tsx
import React from "react";
import i18next from "i18next";
import { initReactI18next, I18nextProvider, useTranslation } from "react-i18next";

const i18n = i18next.createInstance();
i18n.use(initReactI18next).init({
  lng: "en",
  fallbackLng: "en",
  resources: { en: { translation: {} } },
  interpolation: { escapeValue: false },
  react: { useSuspense: false },
  keySeparator: false,
  nsSeparator: false,
});

const TestComponent = () => {
  const { i18n, t } = useTranslation();

  void t;
  void i18n.language;

  return null;
};

export default function EmptyComponent() {
  return (
    <I18nextProvider i18n={i18n}>
      <TestComponent />
    </I18nextProvider>
  );
}
