// apps-benchmark/vite-vue-static/vue-i18n-app/src/components/pages/careers/CareersBenefits.vue
<script setup lang="ts">
const benefits = [
  { label: "Remote-first", value: "Work from anywhere in the world" },
  { label: "Competitive pay", value: "Top-of-market compensation" },
  {
    label: "Open source time",
    value: "20% time for OSS contributions",
  },
];
</script>

<template>
  <div class="mb-12 grid gap-4 md:grid-cols-3">
    <div
      v-for="b in benefits"
      :key="b.label"
      class="rounded-lg border border-border bg-card p-4 text-center"
    >
      <p class="text-sm font-semibold text-foreground">{{ b.label }}</p>
      <p class="text-xs text-muted-foreground">{{ b.value }}</p>
    </div>
  </div>
</template>

// tanstack-start-react-dynamic/tolgee-app/src/components/pages/careers/CareersBenefits.tsx
import { useTranslate } from "@tolgee/react";

export default function CareersBenefits() {
  const { t } = useTranslate();

  const benefits = [
    {
      label: t("careersBenefits.remoteFirst", "Remote-first"),
      value: t("careersBenefits.workFromAnywhere", "Work from anywhere in the world"),
    },
    {
      label: t("careersBenefits.competitivePay", "Competitive pay"),
      value: t("careersBenefits.topOfMarketCompensation", "Top-of-market compensation"),
    },
    {
      label: t("careersBenefits.openSourceTime", "Open source time"),
      value: t("careersBenefits.percentTimeForOss", "20% time for OSS contributions"),
    },
  ];

  return (
    <div className="mb-12 grid gap-4 md:grid-cols-3">
      {benefits.map((b) => (
        <div
          key={b.label}
          className="rounded-lg border border-border bg-card p-4 text-center"
        >
          <p className="text-sm font-semibold text-foreground">{b.label}</p>
          <p className="text-xs text-muted-foreground">{b.value}</p>
        </div>
      ))}
    </div>
  );
}
