// apps-benchmark/vite-solid-base-app/src/pages/Team.tsx
import { lazy, Suspense } from "solid-js";

const TeamHeader = lazy(() => import("../components/pages/team/TeamHeader"));
const TeamGrid = lazy(() => import("../components/pages/team/TeamGrid"));

export default function Team() {
  return (
    <div class="container py-16">
      <Suspense fallback={<div class="h-48 animate-pulse bg-muted/20" />}>
        <TeamHeader />
      </Suspense>

      <Suspense fallback={<div class="h-96 animate-pulse bg-muted/20" />}>
        <TeamGrid />
      </Suspense>
    </div>
  );
}

// apps-benchmark/tanstack-start-react-static/intlayer-compat-react-i18next-app/src/routes/$locale/team.tsx
import { createFileRoute } from "@tanstack/react-router";
import { lazy, Suspense } from "react";

const TeamHeader = lazy(() => import("../../components/pages/team/TeamHeader"));
const TeamGrid = lazy(() => import("../../components/pages/team/TeamGrid"));

export const Route = createFileRoute("/$locale/team")({
  component: Team,
});

function Team() {
  return (
    <div className="container py-16">
      <Suspense fallback={<div className="h-48 animate-pulse bg-muted/20" />}>
        <TeamHeader />
      </Suspense>

      <Suspense fallback={<div className="h-96 animate-pulse bg-muted/20" />}>
        <TeamGrid />
      </Suspense>
    </div>
  );
}
