// results/vite-solid-base-app/bundle/contact/ContactHeader_min.js
import { createComponent as e, template as t } from "solid-js/web";
var n = t("<div class=\"mb-6 rounded-md border border-border bg-muted px-4 py-3 text-center text-sm text-muted-foreground\">⚠️ This page contains mock data for benchmarking purposes only. It is not related to any real business or service.");
function r() {
	return n();
}
var i = t("<h1 class=\"mb-2 text-3xl font-bold text-foreground\">Get in Touch"), a = t("<p class=\"mb-8 text-muted-foreground\">Have ideas, found a bug, or want to contribute a benchmark? Reach out to us at <a href=mailto:contact@intlayer.org class=\"text-primary hover:underline\">contact@intlayer.org</a>.");
function o() {
	return [
		e(r, {}),
		i(),
		a()
	];
}
export { o as default };

// results/tanstack-start-react-static/base-app-tanstack/bundles/contact/ContactHeader_min.js
import { Fragment as e, jsx as t, jsxs as n } from "react/jsx-runtime";
//#region src/components/MockBanner.tsx
var r = () => /* @__PURE__ */ t("div", {
	className: "mb-6 rounded-md border border-border bg-muted px-4 py-3 text-center text-sm text-muted-foreground",
	children: "⚠️ This page contains mock data for benchmarking purposes only. It is not related to any real business or service."
});
//#endregion
//#region src/components/pages/contact/ContactHeader.tsx
function i() {
	return /* @__PURE__ */ n(e, { children: [
		/* @__PURE__ */ t(r, {}),
		/* @__PURE__ */ t("h1", {
			className: "mb-2 text-3xl font-bold text-foreground",
			children: "Get in Touch"
		}),
		/* @__PURE__ */ n("p", {
			className: "mb-8 text-muted-foreground",
			children: [
				"Have ideas, found a bug, or want to contribute a benchmark? Reach out to us at",
				" ",
				/* @__PURE__ */ t("a", {
					href: "mailto:contact@intlayer.org",
					className: "text-primary hover:underline",
					children: "contact@intlayer.org"
				}),
				"."
			]
		})
	] });
}
//#endregion
export { i as default };
