// apps-benchmark/vite-svelte-static/paraglide-js-app/src/components/Layout.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import {
    recordHydrationDuration,
    recordRenderTime,
  } from "test-utils/browser-metrics";
  import { setLocale as setParaglideLocale } from "../paraglide/runtime.js";
  import Footer from "./Footer.svelte";
  import Header from "./Header.svelte";

  let { locale, children } = $props<{
    locale: string;
    children: import("svelte").Snippet;
  }>();

  const renderStart =
    typeof performance !== "undefined" ? performance.now() : 0;

  onMount(() => {
    recordHydrationDuration();
    recordRenderTime("AppRoot", renderStart);
  });

  $effect(() => {
    document.documentElement.lang = locale;
    setParaglideLocale(locale, { reload: false });
  });
</script>

<Header />
{@render children()}
<Footer />

// apps-benchmark/vite-solid-base-app/src/components/Layout.tsx
import { useParams } from "@solidjs/router";
import { createEffect, onMount, type JSX } from "solid-js";
import {
  recordHydrationDuration,
  recordRenderTime,
} from "test-utils/browser-metrics";
import Footer from "./Footer";
import Header from "./Header";

export default function Layout(props: { children?: JSX.Element }) {
  const params = useParams<{ locale: string }>();
  const start = typeof performance !== "undefined" ? performance.now() : 0;

  onMount(() => {
    recordHydrationDuration();
    recordRenderTime("AppRoot", start);
  });

  createEffect(() => {
    document.documentElement.lang = params.locale ?? "en";
  });

  return (
    <>
      <Header />
      {props.children}
      <Footer />
    </>
  );
}
