// apps-benchmark/vite-solid-scoped-dynamic/i18next-app/src/pages/Contact.tsx
import { lazy, Suspense } from "solid-js";

const ContactHeader = lazy(
  () => import("../components/pages/contact/ContactHeader"),
);
const ContactForm = lazy(() => import("../components/pages/contact/ContactForm"));

export default function Contact() {
  return (
    <div class="container py-16">
      <div class="mx-auto max-w-2xl">
        <Suspense fallback={<div class="h-48 animate-pulse bg-muted/20" />}>
          <ContactHeader />
        </Suspense>

        <Suspense fallback={<div class="h-96 animate-pulse bg-muted/20" />}>
          <ContactForm />
        </Suspense>
      </div>
    </div>
  );
}

// apps-benchmark/nextjs-static/lingo.dev-app/app/[locale]/contact/page.tsx
import dynamic from "next/dynamic";

const ContactHeader = dynamic(() => import("../../../components/pages/contact/ContactHeader"), {
  loading: () => <div className="h-48 animate-pulse bg-muted/20" />,
});
const ContactForm = dynamic(() => import("../../../components/pages/contact/ContactForm"), {
  loading: () => <div className="h-96 animate-pulse bg-muted/20" />,
});

export default function Contact() {
  return (
    <div className="container py-16">
      <div className="mx-auto max-w-2xl">
        <ContactHeader />

        <ContactForm />
      </div>
    </div>
  );
}
