// apps-benchmark/vite-solid-scoped-dynamic/i18next-app/src/hooks/usePerformanceMeasure.ts
import { onMount } from "solid-js";

export function usePerformanceMeasure(name: string) {
  if (typeof performance !== "undefined" && performance.mark) {
    performance.mark(`${name}-start`);
  }

  onMount(() => {
    if (
      typeof performance !== "undefined" &&
      performance.mark &&
      performance.measure
    ) {
      performance.mark(`${name}-end`);
      try {
        performance.measure(`${name}-render`, `${name}-start`, `${name}-end`);
      } catch {
        // Suppress errors if marks are missing or duplicated
      }
    }
  });
}

// apps-benchmark/vite-react-base-app/src/hooks/usePerformanceMeasure.ts
import { useLayoutEffect } from "react";

/**
 * Custom hook to measure the render-to-layout duration of a component.
 * It uses the Browser User Timing API (performance.mark/measure).
 *
 * @param name The name of the measurement (e.g., 'HeroComponent')
 */
export function usePerformanceMeasure(name: string) {
  // Mark the start of the render phase
  // Note: Since this hook runs inside the component's body,
  // it marks as soon as the functional component is called.
  if (typeof performance !== "undefined" && performance.mark) {
    performance.mark(`${name}-start`);
  }

  useLayoutEffect(() => {
    if (typeof performance !== "undefined" && performance.mark && performance.measure) {
      // Mark the end after the browser has applied DOM mutations
      performance.mark(`${name}-end`);

      try {
        performance.measure(`${name}-render`, `${name}-start`, `${name}-end`);
      } catch (e) {
        // Suppress errors if marks are missing or duplicated
      }
    }
  }, [name]);
}
