// tanstack-start-react-dynamic/use-intl-app/src/components/pages/careers/OpenPositions.tsx
import { useTranslations } from "use-intl";

export default function OpenPositions() {
  const t = useTranslations("open-positions");

  const openings = [
    {
      title: t("seniorFrontendEngineer"),
      location: t("remote"),
      type: t("fullTime"),
      dept: t("engineering"),
      desc: t("seniorFrontendEngineer"), // Wait, en.ts has seniorFrontendEngineer: "Senior Frontend Engineer" but no description key?
      // Actually, en.ts has: seniorFrontendEngineer: "Senior Frontend Engineer",
      // buildAndMaintainOurBenchmarking: "Build and maintain our...",
      // Let's use those.
      description: t("buildAndMaintainOurBenchmarking"),
    },
    {
      title: t("backendEngineer"),
      location: t("remote"),
      type: t("fullTime"),
      dept: t("engineering"),
      description: t("designAndScaleOurCloud"),
    },
    {
      title: t("technicalWriter"),
      location: t("remote"),
      type: t("partTime"),
      dept: t("documentation"),
      description: t("createComprehensiveGuidesApiReferences"),
    },
    {
      title: t("devrelEngineer"),
      location: t("sanFranciscoRemote"),
      type: t("fullTime"),
      dept: t("community"),
      description: t("engageWithTheI18nCommunity"),
    },
    {
      title: t("qaEngineer"),
      location: t("remote"),
      type: t("fullTime"),
      dept: t("engineering"),
      description: t("ensureTheAccuracyAndReliability"),
    },
  ];

  return (
    <>
      <h2 className="mb-6 text-2xl font-bold text-foreground">
        {t("openPositions")}
      </h2>
      <div className="space-y-4">
        {openings.map((o) => (
          <div
            key={o.title}
            className="flex flex-col gap-3 rounded-lg border border-border bg-card p-6 md:flex-row md:items-center md:justify-between"
          >
            <div>
              <h3 className="text-base font-semibold text-foreground">
                {o.title}
              </h3>
              <p className="text-sm text-muted-foreground">{o.description}</p>
              <div className="mt-2 flex gap-2">
                <span className="rounded bg-accent px-2 py-0.5 text-xs text-accent-foreground">
                  {o.dept}
                </span>
                <span className="rounded bg-accent px-2 py-0.5 text-xs text-accent-foreground">
                  {o.location}
                </span>
                <span className="rounded bg-accent px-2 py-0.5 text-xs text-accent-foreground">
                  {o.type}
                </span>
              </div>
            </div>
            <button
              type="button"
              className="shrink-0 rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground hover:opacity-90 transition-opacity"
            >
              {t("applyNow")}
            </button>
          </div>
        ))}
      </div>
    </>
  );
}

// apps-benchmark/vite-solid-dynamic/solid-intlayer-app/src/components/pages/careers/OpenPositions.tsx
import { useIntlayer } from 'solid-intlayer';
import { For } from 'solid-js';

export default function OpenPositions() {
  const content = useIntlayer('open-positions');

  const openings = [
    {
      title: content().seniorFrontendEngineer.value,
      location: content().remote.value,
      type: 'Full-time',
      dept: content().engineering.value,
      desc: content().buildAndMaintainOurBenchmarking.value,
    },
    {
      title: content().backendEngineer.value,
      location: content().remote.value,
      type: 'Full-time',
      dept: content().engineering.value,
      desc: content().designAndScaleOurCloud.value,
    },
    {
      title: content().technicalWriter.value,
      location: content().remote.value,
      type: 'Part-time',
      dept: content().documentation.value,
      desc: content().createComprehensiveGuidesApiReferences.value,
    },
    {
      title: content().devrelEngineer.value,
      location: content().sanFranciscoRemote.value,
      type: 'Full-time',
      dept: content().community.value,
      desc: content().engageWithTheI18nCommunity.value,
    },
    {
      title: content().qaEngineer.value,
      location: content().remote.value,
      type: 'Full-time',
      dept: content().engineering.value,
      desc: content().ensureTheAccuracyAndReliability.value,
    },
  ];

  return (
    <>
      <h2 class="mb-6 text-2xl font-bold text-foreground">
        {content().openPositions}
      </h2>
      <div class="space-y-4">
        <For each={openings}>
          {(o) => (
            <div class="flex flex-col gap-3 rounded-lg border border-border bg-card p-6 md:flex-row md:items-center md:justify-between">
              <div>
                <h3 class="text-base font-semibold text-foreground">
                  {o.title}
                </h3>
                <p class="text-sm text-muted-foreground">{o.desc}</p>
                <div class="mt-2 flex gap-2">
                  <span class="rounded bg-accent px-2 py-0.5 text-xs text-accent-foreground">
                    {o.dept}
                  </span>
                  <span class="rounded bg-accent px-2 py-0.5 text-xs text-accent-foreground">
                    {o.location}
                  </span>
                  <span class="rounded bg-accent px-2 py-0.5 text-xs text-accent-foreground">
                    {o.type}
                  </span>
                </div>
              </div>
              <button
                type="button"
                class="shrink-0 rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground transition-opacity hover:opacity-90"
              >
                {content().applyNow}
              </button>
            </div>
          )}
        </For>
      </div>
    </>
  );
}
