// results/tanstack-start-react-static/paraglide-app/bundles/pages/PricingTiers_min.js
import "react";
import { Fragment as e, jsx as t, jsxs as n } from "react/jsx-runtime";
//#region src/components/pages/pricing/PricingTiers.tsx
var r = [
	{
		name: "Starter",
		price: "$0",
		period: "forever",
		features: [
			"5 benchmark runs/day",
			"3 libraries",
			"Community support",
			"Public results"
		]
	},
	{
		name: "Pro",
		price: "$29",
		period: "/month",
		features: [
			"Unlimited runs",
			"All libraries",
			"Priority support",
			"Private results",
			"CI integration",
			"Historical data"
		],
		highlighted: !0
	},
	{
		name: "Enterprise",
		price: "Custom",
		period: "",
		features: [
			"Everything in Pro",
			"On-premise option",
			"SSO & SAML",
			"Dedicated account manager",
			"Custom SLAs",
			"Audit logs",
			"Training sessions"
		]
	}
];
function i() {
	return /* @__PURE__ */ t("div", {
		className: "grid gap-6 md:grid-cols-3",
		children: r.map((e) => /* @__PURE__ */ n("div", {
			className: `flex flex-col rounded-lg border p-6 ${e.highlighted ? "border-primary bg-primary/5 ring-1 ring-primary" : "border-border bg-card"}`,
			children: [
				/* @__PURE__ */ t("h3", {
					className: "text-lg font-semibold text-foreground",
					children: e.name
				}),
				/* @__PURE__ */ n("div", {
					className: "my-4",
					children: [/* @__PURE__ */ t("span", {
						className: "text-3xl font-bold text-foreground",
						children: e.price
					}), /* @__PURE__ */ t("span", {
						className: "text-sm text-muted-foreground",
						children: e.period
					})]
				}),
				/* @__PURE__ */ t("ul", {
					className: "mb-6 flex-1 space-y-2",
					children: e.features.map((e) => /* @__PURE__ */ n("li", {
						className: "flex items-center gap-2 text-sm text-muted-foreground",
						children: [
							/* @__PURE__ */ t("span", {
								className: "text-primary",
								children: "✓"
							}),
							" ",
							e
						]
					}, e))
				}),
				/* @__PURE__ */ t("button", {
					type: "button",
					className: `w-full rounded-md px-4 py-2 text-sm font-medium transition-opacity hover:opacity-90 ${e.highlighted ? "bg-primary text-primary-foreground" : "border border-border text-foreground hover:bg-accent"}`,
					children: e.name === "Enterprise" ? "Contact Sales" : "Get Started"
				})
			]
		}, e.name))
	});
}
//#endregion
//#region src/paraglide/runtime.js
var a = {}, o = [
	"en",
	"de",
	"fr",
	"es",
	"ja",
	"zh",
	"ko",
	"it",
	"pt"
], s = "PARAGLIDE_LOCALE", c = 3456e4, l = [
	"cookie",
	"globalVariable",
	"baseLocale"
], u = [], d, f;
function p(e) {
	if (u.length === 0) return;
	let t = typeof e == "string" ? e : e.href;
	if (d === t) return f;
	let n = new URL(t, "http://dummy.com"), r;
	for (let e of u) if (new a(e.match, n.href).exec(n.href)) {
		r = e;
		break;
	}
	return d = t, f = r, r;
}
function m(e) {
	let t = p(e);
	return t && t.exclude !== !0 && Array.isArray(t.strategy) ? t.strategy : l;
}
var h = void 0;
globalThis.__paraglide = globalThis.__paraglide ?? {}, globalThis.__paraglide.ssr = globalThis.__paraglide.ssr ?? {};
var g, _ = !1, v = () => {
	if (h) {
		let e = h?.getStore()?.locale;
		if (e) return e;
	}
	let e = l;
	typeof window < "u" && window.location?.href && (e = m(window.location.href));
	let t = y(e, typeof window < "u" ? window.location?.href : void 0);
	if (t) return _ || (g = t, _ = !0, x(t, { reload: !1 })), t;
	throw Error("No locale found. Read the docs https://inlang.com/m/gerre34r/library-inlang-paraglideJs/errors#no-locale-found");
};
function y(e, t) {
	let n;
	for (let t of e) {
		if (t === "cookie") n = w();
		else if (t === "baseLocale") n = "en";
		else if (t === "globalVariable" && g !== void 0) n = g;
		else if (E(t) && T.has(t)) {
			let e = T.get(t);
			if (e) {
				let t = e.getLocale();
				if (t instanceof Promise) continue;
				if (t !== void 0) return C(t);
			}
		}
		let e = S(n);
		if (e) return e;
	}
}
var b = (e) => {
	e ? window.location.href = e : window.location.reload();
}, x = (e, t) => {
	let n = {
		reload: !0,
		...t
	}, r;
	try {
		r = v();
	} catch {}
	let i = [], a = l;
	typeof window < "u" && window.location?.href && (a = m(window.location.href));
	for (let t of a) if (t === "globalVariable") g = e;
	else if (t === "cookie") {
		if (typeof document > "u" || typeof window > "u") continue;
		let t = `${s}=${e}; path=/; max-age=${c}`;
		document.cookie = t;
	} else if (t === "baseLocale") continue;
	else if (E(t) && T.has(t)) {
		let n = T.get(t);
		if (n) {
			let r = n.setLocale(e);
			r instanceof Promise && (r = r.catch((e) => {
				throw Error(`Custom strategy "${t}" setLocale failed.`, { cause: e });
			}), i.push(r));
		}
	}
	let o = () => {
		n.reload && window.location && e !== r && b(void 0);
	};
	if (i.length) return Promise.all(i).then(() => {
		o();
	});
	o();
};
function S(e) {
	if (typeof e != "string") return;
	let t = e.toLowerCase();
	for (let e of o) if (e.toLowerCase() === t) return e;
}
function C(e) {
	let t = S(e);
	if (t) return t;
	throw Error(`Invalid locale: ${e}. Expected one of: ${o.join(", ")}`);
}
function w() {
	if (typeof document > "u" || !document.cookie) return;
	let e = document.cookie.match(RegExp(`(^| )${s}=([^;]+)`))?.[2];
	return S(e);
}
var T = /* @__PURE__ */ new Map();
function E(e) {
	return typeof e == "string" && /^custom-[A-Za-z0-9_-]+$/.test(e);
}
//#endregion
//#region scripts/Wrapper.tsx
x("en", { reload: !1 });
function D({ children: n }) {
	return /* @__PURE__ */ t(e, { children: n });
}
//#endregion
//#region src/components/pages/pricing/PricingTiers.wrapper.tsx
function O() {
	return /* @__PURE__ */ t(D, { children: /* @__PURE__ */ t(i, {}) });
}
//#endregion
export { O as default };

// results/vite-solid-base-app/bundle/pages/PricingTiers_min.js
import { className as e, createComponent as t, effect as n, insert as r, template as i } from "solid-js/web";
import { For as a } from "solid-js";
var o = i("<div class=\"grid gap-6 md:grid-cols-3\">"), s = i("<div><h3 class=\"text-lg font-semibold text-foreground\"></h3><div class=my-4><span class=\"text-3xl font-bold text-foreground\"></span><span class=\"text-sm text-muted-foreground\"></span></div><ul class=\"mb-6 flex-1 space-y-2\"></ul><button type=button>"), c = i("<li class=\"flex items-center gap-2 text-sm text-muted-foreground\"><span class=text-primary>✓</span> ");
function l() {
	let i = [
		{
			name: "Starter",
			price: "$0",
			period: "forever",
			features: [
				"5 benchmark runs/day",
				"3 libraries",
				"Community support",
				"Public results"
			]
		},
		{
			name: "Pro",
			price: "$29",
			period: "/month",
			features: [
				"Unlimited runs",
				"All libraries",
				"Priority support",
				"Private results",
				"CI integration",
				"Historical data"
			],
			highlighted: !0
		},
		{
			name: "Enterprise",
			price: "Custom",
			period: "",
			features: [
				"Everything in Pro",
				"On-premise option",
				"SSO & SAML",
				"Dedicated account manager",
				"Custom SLAs",
				"Audit logs",
				"Training sessions"
			]
		}
	];
	return (() => {
		var l = o();
		return r(l, t(a, {
			each: i,
			children: (i) => (() => {
				var o = s(), l = o.firstChild, u = l.nextSibling, d = u.firstChild, f = d.nextSibling, p = u.nextSibling, m = p.nextSibling;
				return r(l, () => i.name), r(d, () => i.price), r(f, () => i.period), r(p, t(a, {
					get each() {
						return i.features;
					},
					children: (e) => (() => {
						var t = c();
						return t.firstChild.nextSibling, r(t, e, null), t;
					})()
				})), r(m, () => i.name === "Enterprise" ? "Contact Sales" : "Get Started"), n((t) => {
					var n = `flex flex-col rounded-lg border p-6 ${i.highlighted ? "border-primary bg-primary/5 ring-1 ring-primary" : "border-border bg-card"}`, r = `w-full rounded-md px-4 py-2 text-sm font-medium transition-opacity hover:opacity-90 ${i.highlighted ? "bg-primary text-primary-foreground" : "border border-border text-foreground hover:bg-accent"}`;
					return n !== t.e && e(o, t.e = n), r !== t.t && e(m, t.t = r), t;
				}, {
					e: void 0,
					t: void 0
				}), o;
			})()
		})), l;
	})();
}
export { l as default };
