// apps-benchmark/vite-vue-dynamic/vue-intlayer-app/src/components/Footer.vue
<script setup lang="ts">
import { computed } from "vue";
import { useRoute } from "vue-router";
import { useIntlayer } from "vue-intlayer";

const route = useRoute();
const currentLocale = computed(() => (route.params.locale as string) || "en");

const {
  description,
  resources,
  contact: contactLabel,
  github,
  methodology,
  contributing,
  footerText,
  appName,
  contactEmail,
} = useIntlayer("footer");

const footerLinks = computed(() => [
  {
    label: github,
    href: "https://github.com/intlayer-org/benchmark-i18n",
    isInternal: false,
  },
  {
    label: methodology,
    to: `/${currentLocale.value}/about`,
    isInternal: true,
  },
  {
    label: contributing,
    to: `/${currentLocale.value}/contact`,
    isInternal: true,
  },
]);
</script>

<template>
  <footer class="mt-20 border-t border-border bg-card">
    <div class="container py-8">
      <div class="grid gap-8 md:grid-cols-3">
        <div>
          <h3 class="mb-2 text-sm font-semibold text-foreground">
            {{ appName }}
          </h3>
          <p class="text-sm text-muted-foreground">
            {{ description }}
          </p>
        </div>
        <div>
          <h3 class="mb-2 text-sm font-semibold text-foreground">
            {{ resources }}
          </h3>
          <ul class="space-y-1">
            <li v-for="linkEl in footerLinks" :key="linkEl.label">
              <router-link
                v-if="linkEl.isInternal"
                :to="linkEl.to!"
                class="text-sm text-muted-foreground hover:text-foreground transition-colors"
              >
                {{ linkEl.label }}
              </router-link>
              <a
                v-else
                :href="linkEl.href"
                target="_blank"
                rel="noreferrer"
                class="text-sm text-muted-foreground hover:text-foreground transition-colors"
              >
                {{ linkEl.label }}
              </a>
            </li>
          </ul>
        </div>
        <div>
          <h3 class="mb-2 text-sm font-semibold text-foreground">
            {{ contactLabel }}
          </h3>
          <p class="text-sm text-muted-foreground">{{ contactEmail }}</p>
        </div>
      </div>
      <div
        class="mt-8 border-t border-border pt-4 text-center text-xs text-muted-foreground"
      >
        {{ footerText }}
      </div>
    </div>
  </footer>
</template>

// apps-benchmark/vite-svelte-static/svelte-intlayer-app/src/components/Footer.svelte
<script lang="ts">
  import { useIntlayer } from "svelte-intlayer";
  import { route } from "$lib/routerStore";

  const footer = useIntlayer("footer");

  const currentLocale = $derived(
    $route.kind === "ok" ? $route.locale : "en",
  );

  const footerLinks = $derived([
    {
      label: $footer.github,
      href: "https://github.com/intlayer-org/benchmark-i18n",
      isInternal: false,
    },
    {
      label: $footer.methodology,
      to: `/${currentLocale}/about`,
      isInternal: true,
    },
    {
      label: $footer.contributing,
      to: `/${currentLocale}/contact`,
      isInternal: true,
    },
  ]);
</script>

<footer class="mt-20 border-t border-border bg-card">
  <div class="container py-8">
    <div class="grid gap-8 md:grid-cols-3">
      <div>
        <h3 class="mb-2 text-sm font-semibold text-foreground">
          {$footer.appName}
        </h3>
        <p class="text-sm text-muted-foreground">
          {$footer.description}
        </p>
      </div>
      <div>
        <h3 class="mb-2 text-sm font-semibold text-foreground">
          {$footer.resources}
        </h3>
        <ul class="space-y-1">
          {#each footerLinks as linkEl, i (i)}
            <li>
              {#if linkEl.isInternal}
                <a
                  href={linkEl.to}
                  class="text-sm text-muted-foreground transition-colors hover:text-foreground"
                >
                  {linkEl.label}
                </a>
              {:else}
                <a
                  href={linkEl.href}
                  target="_blank"
                  rel="noreferrer"
                  class="text-sm text-muted-foreground transition-colors hover:text-foreground"
                >
                  {linkEl.label}
                </a>
              {/if}
            </li>
          {/each}
        </ul>
      </div>
      <div>
        <h3 class="mb-2 text-sm font-semibold text-foreground">
          {$footer.contact}
        </h3>
        <p class="text-sm text-muted-foreground">{$footer.contactEmail}</p>
      </div>
    </div>
    <div
      class="mt-8 border-t border-border pt-4 text-center text-xs text-muted-foreground"
    >
      {$footer.footerText}
    </div>
  </div>
</footer>
