// results/tanstack-start-react-static/base-app-vite-react/bundles/about/AboutHeader_min.js
import { useLayoutEffect as e } from "react";
import { Fragment as t, jsx as n, jsxs as r } from "react/jsx-runtime";
//#region src/hooks/usePerformanceMeasure.ts
function i(t) {
	typeof performance < "u" && performance.mark && performance.mark(`${t}-start`), e(() => {
		if (typeof performance < "u" && performance.mark && performance.measure) {
			performance.mark(`${t}-end`);
			try {
				performance.measure(`${t}-render`, `${t}-start`, `${t}-end`);
			} catch {}
		}
	}, [t]);
}
//#endregion
//#region src/components/pages/about/AboutHeader.tsx
function a() {
	return i("AboutHeader"), r(t, { children: [n("h1", {
		className: "mb-4 text-3xl font-bold text-foreground",
		children: "About This Benchmark"
	}), n("p", {
		className: "mb-8 max-w-3xl text-muted-foreground",
		children: "This is an open-source test application — not a product or a company. Its sole purpose is to provide a realistic, multi-page React app where different i18n libraries can be integrated and measured under identical conditions."
	})] });
}
//#endregion
export { a as default };

// results/vite-solid-primitives-i18n-static/bundle/pages/AboutHeader_min.js
import { template as e } from "solid-js/web";
import { onMount as t } from "solid-js";
function n(e) {
	typeof performance < "u" && performance.mark && performance.mark(`${e}-start`), t(() => {
		if (typeof performance < "u" && performance.mark && performance.measure) {
			performance.mark(`${e}-end`);
			try {
				performance.measure(`${e}-render`, `${e}-start`, `${e}-end`);
			} catch {}
		}
	});
}
var r = e("<h1 class=\"mb-4 text-3xl font-bold text-foreground\">About This Benchmark"), i = e("<p class=\"mb-8 max-w-3xl text-muted-foreground\">This is an open-source test application — not a product or a company. Its sole purpose is to provide a realistic, multi-page React app where different i18n libraries can be integrated and measured under identical conditions.");
function a() {
	return n("AboutHeader"), [r(), i()];
}
export { a as default };
