// apps-benchmark/vite-svelte-dynamic/svelte-i18n-app/src/components/Layout.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import {
    recordHydrationDuration,
    recordRenderTime,
  } from "test-utils/browser-metrics";
  import Footer from "./Footer.svelte";
  import Header from "./Header.svelte";

  let { locale, children } = $props<{
    locale: string;
    children: import("svelte").Snippet;
  }>();

  const renderStart =
    typeof performance !== "undefined" ? performance.now() : 0;

  onMount(() => {
    recordHydrationDuration();
    recordRenderTime("AppRoot", renderStart);
  });

  $effect(() => {
    document.documentElement.lang = locale;
  });
</script>

<Header />
{@render children()}
<Footer />

// apps-benchmark/vite-vue-base-app/src/components/Layout.vue
<script setup lang="ts">
import { onMounted, watch, ref, onBeforeMount } from "vue";
import { useRoute } from "vue-router";
import {
  recordHydrationDuration,
  recordRenderTime,
} from "test-utils/browser-metrics";
import Footer from "./Footer.vue";
import Header from "./Header.vue";

const route = useRoute();
const renderStart = ref(0);

onBeforeMount(() => {
  renderStart.value = typeof performance !== "undefined" ? performance.now() : 0;
});

onMounted(() => {
  recordHydrationDuration();
  recordRenderTime("AppRoot", renderStart.value);
});

watch(
  () => route.params.locale,
  (newLocale) => {
    if (newLocale) {
      document.documentElement.lang = newLocale as string;
    }
  },
  { immediate: true }
);
</script>

<template>
  <Header />
  <router-view />
  <Footer />
</template>
