// apps-benchmark/vite-solid-static/tolgee-app/src/components/Layout.tsx
import { useParams } from '@solidjs/router';
import { createEffect, onMount, type JSX } from 'solid-js';
import { setTolgeeLanguage, tolgee } from '../i18n';
import {
  recordHydrationDuration,
  recordRenderTime,
} from 'test-utils/browser-metrics';
import Footer from './Footer';
import Header from './Header';

export default function Layout(props: { children?: JSX.Element }) {
  const params = useParams<{ locale: string }>();
  const start = typeof performance !== 'undefined' ? performance.now() : 0;

  onMount(() => {
    recordHydrationDuration();
    recordRenderTime('AppRoot', start);
  });

  createEffect(() => {
    const loc = params.locale ?? 'en';
    document.documentElement.lang = loc;
    void tolgee.changeLanguage(loc).then(() => {
      setTolgeeLanguage(loc);
    });
  });

  return (
    <>
      <Header />
      {props.children}
      <Footer />
    </>
  );
}

// apps-benchmark/vite-vue-dynamic/tolgee-app/src/components/Layout.vue
<script setup lang="ts">
import { onMounted, watch, ref, onBeforeMount } from "vue";
import { useRoute } from "vue-router";
import { tolgee } from "../i18n";
import {
  recordHydrationDuration,
  recordRenderTime,
} from "test-utils/browser-metrics";
import Footer from "./Footer.vue";
import Header from "./Header.vue";

const route = useRoute();
const renderStart = ref(0);

onBeforeMount(() => {
  renderStart.value = typeof performance !== "undefined" ? performance.now() : 0;
});

onMounted(() => {
  recordHydrationDuration();
  recordRenderTime("AppRoot", renderStart.value);
});

watch(
  () => route.params.locale,
  (newLocale) => {
    if (newLocale) {
      document.documentElement.lang = newLocale as string;
      tolgee.changeLanguage(newLocale as string);
    }
  },
  { immediate: true }
);
</script>

<template>
  <Header />
  <router-view />
  <Footer />
</template>
